import { index, pgTable, text, timestamp, unique, uuid } from "drizzle-orm/pg-core";
import { tenants } from "./tenancy";
import { users } from "./auth";

// Decisions on CROSS-COURSE LINKS: one course's lesson mentions another course, and the owner says
// whether that mention becomes a link a learner sees. Per tenant, because a link is only ever
// offered inside the brand that holds both ends of it.
//
// The candidates themselves are NOT here. They live in the committed registry
// (src/lib/cross-links.ts, generated by `pnpm gen:cross-links` from the lessons in the database),
// the same split the citation boards use: the finding is a property of the text and belongs in git
// where a diff can show it changing, and only the DECISION is per-tenant state that belongs in a row.
//
// TWO TABLES, AND WHY.
//
// `cross_link_approvals` follows ebook_approvals exactly: a row EXISTS only when the link has been
// approved, so absence is the default and the default is that nothing renders. A boolean column
// instead would make "not yet reviewed" and "reviewed and rejected" look identical to a bug reading
// the wrong column, and a missing row would then read as approved-by-omission.
//
// But a reviewer also has to be able to say NO and have the item stop coming back, and that state
// cannot live on the approval row without giving the approval row a meaning other than "approved".
// So a rejection is its own row in its own table. The asymmetry of the two failure modes is the
// whole argument:
//
//   forget to consult cross_link_dismissals  ->  a rejected candidate reappears in the owner's
//                                                queue. Visible, annoying, and safe.
//   forget a `decision = 'approved'` filter  ->  a rejected link renders to learners. Invisible,
//                                                and exactly what this feature exists to prevent.
//
// One table with a decision column makes the second mistake possible in every query that ever reads
// it. Two tables make it unrepresentable: the render path only ever reads approvals, and there is no
// column on that table whose value could turn a row into a rejection.
//
// A decision FLIPS rather than accumulates: approving deletes any dismissal for the same triple and
// dismissing deletes any approval, so the two tables can never both hold the same candidate and
// there is no precedence rule for a reader to get wrong.
//
// IDENTITY is the triple (source course slug, source lesson slug, target course slug), not an
// opaque key from the registry. The render path can then answer "what did the owner approve for
// THIS lesson" with one indexed read and no dependency on the registry being in sync, and a
// regenerated registry never silently un-approves anything. The write path still checks the triple
// against the registry (src/app/api/admin/cross-links/route.ts) so a POST cannot mint a link
// between two courses that no lesson actually mentions.

export const crossLinkApprovals = pgTable(
  "cross_link_approvals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    /** The course whose lesson carries the mention. `courses.slug`, as the registry records it. */
    sourceCourseSlug: text("source_course_slug").notNull(),
    /** The lesson inside that course. `lessons.slug`. */
    sourceLessonSlug: text("source_lesson_slug").notNull(),
    /** The course being mentioned, and linked to once approved. */
    targetCourseSlug: text("target_course_slug").notNull(),
    approvedAt: timestamp("approved_at", { withTimezone: true }).notNull().defaultNow(),
    approvedBy: text("approved_by").references(() => users.id, { onDelete: "set null" }),
    /** What was checked before approving. Optional, but the admin form asks for it. */
    note: text("note"),
  },
  (t) => [
    unique("cross_link_approvals_triple_uq").on(
      t.tenantId,
      t.sourceCourseSlug,
      t.sourceLessonSlug,
      t.targetCourseSlug,
    ),
    // The render path's only query: every approved target for one lesson of one course.
    index("cross_link_approvals_source_idx").on(
      t.tenantId,
      t.sourceCourseSlug,
      t.sourceLessonSlug,
    ),
  ],
);

export const crossLinkDismissals = pgTable(
  "cross_link_dismissals",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenants.id, { onDelete: "cascade" }),
    sourceCourseSlug: text("source_course_slug").notNull(),
    sourceLessonSlug: text("source_lesson_slug").notNull(),
    targetCourseSlug: text("target_course_slug").notNull(),
    dismissedAt: timestamp("dismissed_at", { withTimezone: true }).notNull().defaultNow(),
    dismissedBy: text("dismissed_by").references(() => users.id, { onDelete: "set null" }),
    /** Why it was turned down. The board asks for it for the same reason the citation board does:
     *  a decision recorded with no reason stops anyone looking again and explains nothing. */
    reason: text("reason"),
  },
  (t) => [
    unique("cross_link_dismissals_triple_uq").on(
      t.tenantId,
      t.sourceCourseSlug,
      t.sourceLessonSlug,
      t.targetCourseSlug,
    ),
    index("cross_link_dismissals_tenant_idx").on(t.tenantId),
  ],
);

export type CrossLinkApproval = typeof crossLinkApprovals.$inferSelect;
export type CrossLinkDismissal = typeof crossLinkDismissals.$inferSelect;
