// GENERATED by `pnpm gen:ebooks` from docs/, DO NOT EDIT BY HAND.
// The markdown source lives in docs/ (gitignored), so the text is committed here as a
// plain string: the deployed app imports this module and never reads the filesystem.

export const EBOOK_BUYING_COURSES = `# What to Demand From Anyone Selling You a Course

### A buyer's guide for schools and districts, now that anyone can generate a curriculum in an afternoon

*A Learn.WitUS field guide. Draft for review.*

---

## Who this is for

You sign the purchase order. You are not going to read four hundred lessons, and nobody expects you
to. What you need is a way to tell, quickly, whether a vendor's curriculum is what it claims to be.

**Your procurement process was designed for a world where making a course was expensive.** That
assumption did a lot of quiet work. A vendor with two hundred polished lessons and a bibliography had
obviously invested something, and investment was a proxy for care.

That proxy is gone. Two hundred polished lessons with a bibliography is now an afternoon's work, and
the bibliography can be generated too. **Everything your process used as a signal of effort is now
free.** This guide is about what to use instead.

None of it requires you to be a subject expert. All of it can be done by someone with a browser and
twenty minutes.

---

## Part 1: What no longer proves anything

Be blunt about this, because these are the things vendor decks still lead with.

**Volume.** The number of lessons, hours, or modules. Free to produce.

**Polish.** Clean prose, consistent formatting, professional tone. Free.

**A bibliography.** A list of sources at the end of each lesson. **Free, and this is the dangerous
one**, because a bibliography looks exactly like diligence. A generated citation has a real-sounding
author, a real-sounding journal, and a plausible year. Some of them are entirely invented. More often
the source is real and does not say what the lesson claims it says, which is worse, because it
survives every automated check.

**Standards alignment claims.** A vendor saying "aligned to your state standards" costs nothing to
say. Producing a list of codes costs nothing either.

**AI disclosure, either way.** A vendor saying they do not use AI is making a claim you cannot verify
and which probably is not true. A vendor saying they do is being honest about a tool. **Neither tells
you anything about quality.** The right question is never whether AI was used. It is what was done
afterwards.

---

## Part 2: The seven questions

Ask these of any vendor. The answers separate serious providers from resellers of generated content,
and none of them require you to know the subject.

### 1. "Who verified the sources, and how do I see that record?"

**Why it works:** writing a citation and verifying one are different acts, and only the second costs
anything. A serious vendor has a record: who checked what, when, and what they found.

**A good answer** names a process and offers evidence. A vendor who can show you a list of citations
with verification status has done the work.

**A bad answer** is "our team of experts reviews everything." That is a description of hope.

### 2. "Show me a claim you could not verify, and what you did about it."

**Why it works:** every honest curriculum has some. Facts change, sources sit behind paywalls, an
agency does not answer email. A vendor with none is either not looking or not telling you.

**A good answer** produces an example, and shows the hedge is written into the lesson rather than
quietly dropped.

**A bad answer** is that everything checked out.

### 3. "Can a student pass your quizzes without reading the lessons?"

**Why it works:** there are two well-known ways to write a quiz that measures test-taking instead of
learning, and both happen by accident to careful authors.

- **Position.** If most correct answers sit in the same place, a student can click one letter and pass.
- **Length.** The correct answer collects the qualifier and the "because" clause while the distractors
  stay short, so a student clicks the longest option and passes without reading the question.

**A good answer** shows they measure this and can tell you the number.

**A bad answer** is that their questions are written by educators. So are most of the failing ones.

**And this is not a quiz-quality issue.** Every completion statistic, every dashboard average, and
every efficacy claim built on those scores is computed from them. A quiz that can be gamed does not
just fail a student, it makes every number the vendor reports meaningless.

### 4. "When a lesson changes, what happens to its standards alignment?"

**Why it works:** alignment rots silently. A lesson gets cut or rewritten, and the standard it
evidenced is now claimed by nothing. Nothing breaks. The page still renders. **The claim your teachers
rely on is simply no longer true**, and nobody finds out.

**A good answer** describes a check that runs when content changes.

**A bad answer** is that alignment is reviewed annually. A year is a long time to show teachers a
false claim.

### 5. "What does this curriculum say it cannot do?"

**Why it works:** it tests calibration, which is the one thing generated content cannot cheaply fake.
Confident prose is now free. **Knowing the limits of your own material is not.**

**A good answer** is specific: what the course does not cover, what it does not certify, where the
evidence is thin.

**A bad answer** is a list of benefits.

### 6. "Who is accountable when something is wrong, and how do I report it?"

**Why it works:** every curriculum has errors. What differs is whether there is a route for them.

**A good answer** is a named process with a turnaround, and evidence of corrections actually made.

**A bad answer** is a support email address.

### 7. "What happens to our students' data, and what do you do with their work?"

**Why it works:** it is the question with legal consequences, and it is where a thin vendor is
thinnest.

**A good answer** is specific about what is collected, who can see it, how long it is kept, whether it
trains anything, and what happens when you leave. It can also say, precisely, who can see a
student's own notes and annotations on the lessons, and how a family takes that work with them
when they go. Student work is data too, and the vendor who has thought about it can answer in one
sentence.

**A bad answer** points at a privacy policy.

---

## Part 3: Verify it yourself in twenty minutes

You do not need the vendor's cooperation for any of this.

**Minutes 1 to 5: the citation spot check.**
Open three lessons. Pick one source from each. Then:

1. Does it exist? Search the title and author.
2. Does the link resolve?
3. **Open it and find the sentence the lesson is relying on.**

Step three is the whole test. Most people stop at step two. **If you cannot find the supporting
sentence in ten minutes on any one of three tries, ask the vendor to show you where it is.** Their
answer will tell you a great deal.

**Minutes 6 to 10: the quiz test.**
Open a quiz and do two things without reading any questions:

1. Click the first option every time. Record the score.
2. Retake it clicking the longest option every time. Record the score.

With four options, guessing scores about 25 percent. **If either strategy scores much above that, the
quiz is measuring something other than learning**, and so is every statistic derived from it.

**Minutes 11 to 15: the standards check.**
Take one claimed standard and one lesson that claims it. Read the standard's actual text, then the
lesson. Ask whether a teacher would agree the lesson teaches that. Alignment lists are often generated
by matching keywords.

**Minutes 16 to 20: the honesty check.**
Search the material for the words "may," "approximately," "as of," "verify," and "we could not."
**A curriculum with none of them is not more accurate than one with some.** It is less careful about
saying so.

---

## Part 4: Red flags

- **A bibliography with no dates checked.** Sources are cited but nothing records when anyone last
  confirmed them.
- **Perfect standards coverage.** Every course aligned to everything is a keyword match, not an
  analysis. Honest alignment has gaps and says so.
- **No stated limits anywhere.**
- **Efficacy claims with no study behind them.** "Improves outcomes by 40 percent" needs a citation,
  a sample, and a method, or it is a number someone chose.
- **Testimonials instead of evidence.**
- **Reluctance to let you see a lesson before purchase.**
- **An answer to question 3 that reframes the question.** Anyone who has thought about assessment
  integrity recognises it immediately. Anyone who has not will explain that their questions are
  rigorous.

---

## Part 5: What to put in the contract

Turn the questions into obligations. Suggested, not legal advice, and worth taking to your counsel:

- **A correction turnaround.** A named window for factual errors once reported.
- **Alignment maintenance.** Standards claims are re-verified when lessons change, not annually.
- **Source verification evidence**, available on request.
- **Notice of material change.** You are told when content your teachers rely on is substantively
  revised.
- **Data terms in the contract**, not by reference to a policy page the vendor can edit.
- **An exit clause with your data.** What you get back, in what format, and when.

---

## The one-page version

Before you sign, you should be able to answer:

- [ ] Has anyone other than the author verified the sources, and can I see that record?
- [ ] Did I open three citations myself and find the supporting sentence?
- [ ] Did I try to beat a quiz without reading it, and did I fail?
- [ ] Does a standards claim survive when a lesson changes?
- [ ] Can the vendor tell me what their material does not do?
- [ ] Is there a real route for reporting errors, with evidence of past corrections?
- [ ] Do I know exactly what happens to student data?

**If you can only do one thing, do the citation spot check.** It takes five minutes, it needs no
cooperation from the vendor, and it is the single most informative thing you can learn about how a
curriculum was made.

---

## Where Learn.WitUS fits

We built the checks above into the platform because we needed them ourselves, not because buyers asked.

Citations are extracted from every staged course into a list that a person works through, and a
citation cannot be marked verified without writing down what was found. Invited reviewers can verify a
course's sources without being given access to anything else. Quiz banks are measured on both the
position and the length strategy, and a bank that can be beaten fails the build. Standards claims
carry a rule that a course must either map to a standard or state in one line why it does not.

Student work stays the student's: notes and annotations are private to their author unless the
author shares a specific note with a teacher, one note at a time; guardians see what a teacher sent
their child and nothing the child wrote privately; and every learner can download their own notes
as a plain file whenever they like. And on the rare occasion we open a course before its source
review has finished, every page of that course says so, in words, until the review is done. The
review queue does not quietly shrink to fit a launch calendar.

**We would rather you ask us the seven questions than take our word for any of it.** That is the point
of writing them down.

---

*Draft for BAM's review. No statistics, testimonials, prices or efficacy claims appear in this
document. Adding one would contradict Part 4.*
`;
