// GENERATED by `pnpm gen:cross-links` from the lessons in the database, DO NOT EDIT BY HAND.
// Regenerate after adding or rewriting courses, then commit this file.
// The types and the tenant-resolution rules live in src/lib/cross-links.ts.
//
// EMPTY UNTIL THE FIRST RUN. The generator reads `lessons.text_content`, so it needs a database
// connection (`pnpm gen:cross-links`, which loads .env.local exactly like `pnpm gen:citations`).
// /admin/cross-links says so on its empty state rather than looking like a board with no work left.

import type { CrossLinkCandidate } from "@/lib/cross-links";

/** When this registry was last rebuilt, so the board can say how old its queue is. */
export const CROSS_LINKS_GENERATED_AT: string | null = null;

export const CROSS_LINK_CANDIDATES: CrossLinkCandidate[] = [];
