// AUTO-GENERATED by scripts/gen-standards-index.ts — do not edit by hand.
// Regenerate with `pnpm gen:standards` after adding a jurisdiction file to this directory.

import { JURISDICTION as j_ar } from "./ar";
import { JURISDICTION as j_az } from "./az";
import { JURISDICTION as j_ca } from "./ca";
import { JURISDICTION as j_dc } from "./dc";
import { JURISDICTION as j_fl } from "./fl";
import { JURISDICTION as j_il } from "./il";
import { JURISDICTION as j_in } from "./in";
import { JURISDICTION as j_mi } from "./mi";
import { JURISDICTION as j_ny } from "./ny";
import { JURISDICTION as j_pa } from "./pa";
import { JURISDICTION as j_tx } from "./tx";

import type { JurisdictionFile } from "../types";

export const JURISDICTION_FILES: JurisdictionFile[] = [j_ar, j_az, j_ca, j_dc, j_fl, j_il, j_in, j_mi, j_ny, j_pa, j_tx];
