// AUTO-GENERATED by scripts/gen-standards-index.ts — do not edit by hand.
// Regenerate with `pnpm gen:standards` after adding a jurisdiction file to this directory.

import { JURISDICTION as j_ar } from "./ar";
import { JURISDICTION as j_az } from "./az";
import { JURISDICTION as j_ca } from "./ca";
import { JURISDICTION as j_dc } from "./dc";
import { JURISDICTION as j_in } from "./in";
import { JURISDICTION as j_tx } from "./tx";

import type { JurisdictionFile } from "../types";

export const JURISDICTION_FILES: JurisdictionFile[] = [j_ar, j_az, j_ca, j_dc, j_in, j_tx];
