// gen:standards — regenerate the COMMITTED jurisdiction index for the standards finder.
//
//   pnpm gen:standards
//
// Same pattern as gen:future-work: the app cannot glob TypeScript modules at request time, so a
// DEV-TIME step discovers every `src/lib/standards/data/<state>.ts` file and writes
// `src/lib/standards/data/index.generated.ts`, which IS committed and is the only thing the app
// imports. Adding a jurisdiction is therefore: write `data/az.ts` (exporting `JURISDICTION`),
// run `pnpm gen:standards`, commit — zero hand-edited code change.
//
// The generator validates the one contract it depends on (the file exports a `JURISDICTION`
// const) by grepping the source; deeper integrity (claims resolve, codes unique, states match
// file names) is enforced by tests/isolation/standards.test.ts.

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DATA_DIR = join(import.meta.dirname, "..", "src", "lib", "standards", "data");

const files = readdirSync(DATA_DIR)
  .filter((f) => f.endsWith(".ts") && f !== "index.generated.ts")
  .sort();

const entries = files.map((f) => {
  const base = f.replace(/\.ts$/, "");
  const src = readFileSync(join(DATA_DIR, f), "utf8");
  if (!/export const JURISDICTION\b/.test(src)) {
    console.error(`${f}: must export \`export const JURISDICTION: JurisdictionFile\``);
    process.exit(1);
  }
  // "in" is a reserved word; prefix every binding for uniformity.
  return { base, binding: `j_${base.replace(/[^a-zA-Z0-9]/g, "_")}` };
});

const out = [
  "// AUTO-GENERATED by scripts/gen-standards-index.ts, do not edit by hand.",
  "// Regenerate with `pnpm gen:standards` after adding a jurisdiction file to this directory.",
  "",
  ...entries.map((e) => `import { JURISDICTION as ${e.binding} } from "./${e.base}";`),
  "",
  'import type { JurisdictionFile } from "../types";',
  "",
  `export const JURISDICTION_FILES: JurisdictionFile[] = [${entries.map((e) => e.binding).join(", ")}];`,
  "",
].join("\n");

writeFileSync(join(DATA_DIR, "index.generated.ts"), out);
console.log(
  `gen:standards, wrote data/index.generated.ts with ${entries.length} jurisdiction(s): ${entries
    .map((e) => e.base)
    .join(", ")}`,
);
