// gen:future-work — regenerate the COMMITTED future-work content modules from the local planning
// notes in `plans/future-courses/` (which is GITIGNORED and therefore does not exist in a deploy).
//
//   pnpm gen:future-work
//
// Why this exists: /admin/future renders these proposals in the deployed app, so the content cannot
// be read from `plans/` at runtime — that directory isn't in the repo, isn't in the build, and isn't
// on the server. This script is a DEV-TIME step: it reads the local markdown once and writes plain
// TypeScript string modules under `src/lib/future-work-content/`, which ARE committed and are the only
// thing the app ever imports. Nothing in `src/` touches the filesystem or `plans/` at request time.
//
// Re-run it after editing the source notes, then commit the regenerated modules.

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const OUT_DIR = join(ROOT, "src", "lib", "future-work-content");

// `--from <dir>` overrides. Otherwise: this checkout's plans/, then the main checkout's plans/
// (a git worktree never has the gitignored dir, but it sits three levels under the main one).
const fromFlag = process.argv.indexOf("--from");
const SRC_DIRS =
  fromFlag !== -1 && process.argv[fromFlag + 1]
    ? [process.argv[fromFlag + 1]]
    : [join(ROOT, "plans", "future-courses"), join(ROOT, "..", "..", "..", "plans", "future-courses")];

function sourceDir(): string {
  for (const d of SRC_DIRS) {
    try {
      readdirSync(d);
      return d;
    } catch {
      // try next
    }
  }
  console.error(`No plans/future-courses/ found. Looked in:\n  ${SRC_DIRS.join("\n  ")}`);
  process.exit(1);
}

/** Escape a markdown body for embedding in a TS template literal. */
function lit(s: string): string {
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

const slugify = (s: string) =>
  s
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-");

/** One-line summary: the "Who she is." sentence, de-bolded and trimmed. */
function summarize(body: string): string {
  const m = body.match(/\*\*Who she is\.\*\*\s*([\s\S]*?)(?:\n\n|$)/);
  const raw = m
    ? m[1]
    : (body
        .split("\n")
        .find((l) => l.trim() && !l.startsWith("http") && !l.startsWith("#")) ?? "");
  const flat = raw.replace(/\*\*/g, "").replace(/\*/g, "").replace(/\s+/g, " ").trim();
  if (flat.length <= 160) return flat;
  // Cut on a word boundary — sentence-splitting mangles "J.P.", "B.S.", "John W. Rogers".
  const head = flat.slice(0, 157);
  return head.slice(0, head.lastIndexOf(" ")).replace(/[,;:]$/, "") + "…";
}

const header = (from: string) =>
  `// GENERATED by \`pnpm gen:future-work\` from ${from} — DO NOT EDIT BY HAND.\n` +
  `// The source notes live in the gitignored \`plans/\` dir, so the content is committed here as\n` +
  `// plain strings: the deployed app imports this module and never reads the filesystem.\n\n`;

function main() {
  const dir = sourceDir();
  const sdtw = join(dir, "she-did-the-work");
  mkdirSync(OUT_DIR, { recursive: true });

  // ── She Did The Work: the proposal + one seed file per subject ───────────────────────────────
  const proposal = readFileSync(join(sdtw, "00-course-proposals.md"), "utf8").trim();
  const subjectFiles = readdirSync(sdtw)
    .filter((f) => f.endsWith(".md") && !f.startsWith("00-"))
    .sort();

  const subjects = subjectFiles.map((f) => {
    const name = f.replace(/\.md$/, "");
    const body = readFileSync(join(sdtw, f), "utf8").trim();
    return { key: slugify(name), name, summary: summarize(body), body };
  });

  let out = header("plans/future-courses/she-did-the-work/");
  out += `/** The full "She Did the Work" course-proposal document (9 proposed courses, the build order,\n *  the 14 factual errors in the source calendar, and the rights/permissions table). */\n`;
  out += `export const SHE_DID_THE_WORK_PROPOSAL = \`${lit(proposal)}\`;\n\n`;
  out += `export interface SubjectSeed {\n  /** Stable slug, e.g. "ava-duvernay". */\n  key: string;\n  name: string;\n  summary: string;\n  /** The full seed file: sources, fact-checks, course concept. */\n  body: string;\n}\n\n`;
  out += `/** One research seed file per woman in the calendar (${subjects.length}). */\nexport const SHE_DID_THE_WORK_SUBJECTS: SubjectSeed[] = [\n`;
  for (const s of subjects) {
    out += `  {\n    key: ${JSON.stringify(s.key)},\n    name: ${JSON.stringify(s.name)},\n    summary: ${JSON.stringify(s.summary)},\n    body: \`${lit(s.body)}\`,\n  },\n`;
  }
  out += `];\n`;
  writeFileSync(join(OUT_DIR, "she-did-the-work.ts"), out);

  // ── Standalone proposals (top-level *.md) ────────────────────────────────────────────────────
  // AUTO-DISCOVERED, deliberately. These used to be two hardcoded filenames, which meant every new
  // planning note BAM dropped in `plans/future-courses/` was SILENTLY IGNORED by /admin/future until
  // someone remembered to edit this script — the note looked filed but was invisible in the app.
  // Now every top-level `.md` becomes an item automatically. Add a note, run `pnpm gen:future-work`,
  // and it shows up. No code change, nothing to forget.
  const proposalFiles = readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .sort();

  let out2 = header("plans/future-courses/*.md (auto-discovered — add a .md, re-run, done)");
  out2 += `export interface ProposalDoc {\n  /** Stable key: the filename without .md. Used as the /admin/future item key. */\n  key: string;\n  /** Human title: the doc's first \`# heading\`, else the de-slugged filename. */\n  title: string;\n  /** First real line of prose, for the card. */\n  summary: string;\n  body: string;\n  provenance: string;\n}\n\n`;
  out2 += `export const PROPOSAL_DOCS: ProposalDoc[] = [\n`;
  for (const f of proposalFiles) {
    const body = readFileSync(join(dir, f), "utf8").trim();
    if (!body) continue;
    const key = f.replace(/\.md$/, "");
    // Title: prefer the doc's own H1; fall back to the filename, de-slugged.
    const h1 = body.match(/^#\s+(.+)$/m)?.[1]?.trim();
    const title = h1 ?? key.replace(/-/g, " ").replace(/^\w/, (c) => c.toUpperCase());
    out2 += `  {\n    key: ${JSON.stringify(key)},\n    title: ${JSON.stringify(title)},\n    summary: ${JSON.stringify(summarize(body))},\n    body: \`${lit(body)}\`,\n    provenance: ${JSON.stringify(`plans/future-courses/${f}`)},\n  },\n`;
  }
  out2 += `];\n`;
  writeFileSync(join(OUT_DIR, "proposals.ts"), out2);

  console.log(`Wrote src/lib/future-work-content/she-did-the-work.ts (${subjects.length} subjects) + proposals.ts`);
}

main();
