// gen:ebooks — regenerate the COMMITTED ebook content modules from the markdown in docs/.
//
//   pnpm gen:ebooks
//
// Same pattern, and the same reason, as gen:future-work: `docs/` is GITIGNORED, so the app cannot
// read the markdown at runtime. This is a dev-time step that writes plain TypeScript string modules
// under src/lib/ebook-content/, which ARE committed and are the only thing the app imports.
//
// Re-run after editing an ebook, then commit the regenerated module.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dirname, "..");
const OUT = join(ROOT, "src", "lib", "ebook-content");

/** Source markdown → generated module. Add a line here when you add an ebook. */
const EBOOKS: { src: string; out: string; varName: string }[] = [
  { src: "docs/ebook-ai-course-creation.md", out: "ai-course-creation.ts", varName: "EBOOK_AI_COURSE_CREATION" },
  { src: "docs/ebook-buying-courses.md", out: "buying-courses.ts", varName: "EBOOK_BUYING_COURSES" },
];

const header =
  "// GENERATED by `pnpm gen:ebooks` from docs/, DO NOT EDIT BY HAND.\n" +
  "// The markdown source lives in docs/ (gitignored), so the text is committed here as a\n" +
  "// plain string: the deployed app imports this module and never reads the filesystem.\n\n";

mkdirSync(OUT, { recursive: true });
for (const e of EBOOKS) {
  const body = readFileSync(join(ROOT, e.src), "utf-8");
  const esc = body.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
  writeFileSync(join(OUT, e.out), `${header}export const ${e.varName} = \`${esc}\`;\n`);
  console.log(`wrote src/lib/ebook-content/${e.out}`);
}
