// gen:citations — regenerate the COMMITTED citation registry from the lessons in the DATABASE.
//
//   pnpm gen:citations              # every course in STAGED_COURSES
//   pnpm gen:citations --dry-run    # report counts, write nothing
//
// WHY THE DATABASE AND NOT scripts/data/*-course.ts. A large part of this catalog is not committed
// TypeScript: BVC episodes come from CSVs in the gitignored content/bvc/, the health courses are
// generated by gen-health-data.ts, FAA and the languages have their own seeders. Four of the twelve
// courses BAM is enrolled in fall in that category. A generator reading only the committed course
// modules would silently cover about two thirds of the library and report success, which is exactly
// the class of failure this feature exists to catch.
//
// The output module is committed and is all the app ever imports, so nothing reads the database at
// request time. Re-run this after editing any staged course's sources, then commit the result.

import { mkdirSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { join } from "node:path";
import { neonConfig, Pool } from "@neondatabase/serverless";
import { asc, eq, inArray } from "drizzle-orm";
import { drizzle } from "drizzle-orm/neon-serverless";
import ws from "ws";
import * as schema from "../src/db/schema";
import { STAGED_COURSES } from "../src/lib/citations";
import { resolveDbUrl } from "./db-url";

const OUT_DIR = join(import.meta.dirname, "..", "src", "lib", "citation-content");

/** A citation entry, normalized for hashing: whitespace collapsed, markdown emphasis stripped. */
function normalize(entry: string): string {
  return entry
    .replace(/\*+/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

function keyFor(courseSlug: string, entry: string): string {
  const h = createHash("sha256").update(normalize(entry)).digest("hex").slice(0, 12);
  return `${courseSlug}:${h}`;
}

const URL_RE = /(https?:\/\/[^\s)\]]+|10\.\d{4,}\/[^\s)\]]+)/;

/** Looks like a reference rather than prose: an APA year, an n.d., a URL, or a DOI. */
const REFERENCE_SHAPED = /\((?:n\.d\.|\d{4}[a-z]?)|https?:\/\/|10\.\d{4,}\//i;
/** A bold-only line inside a Sources block is a sub-heading (Law, Science, Labour), not a source. */
const SUBHEADING = /^\*\*[^*]+\*\*:?$/;

/**
 * Pull the citation entries out of a lesson body.
 *
 * A Sources block is a `## Sources` / `## References` heading and everything until the next heading.
 * Getting the ENTRY shape right matters more than it looks, because the catalog uses three:
 *
 *   1. Bulleted APA entries. The house style, and what the first version of this parser assumed.
 *   2. UNBULLETED APA paragraphs, one per blank-line-separated block (langgraph-triage-agent).
 *   3. PROSE that names sources inline with URLs (nasm-cpt's "Sources & Further Reading").
 *
 * The bullets-only version reported 0 citations for three staged courses that plainly have them,
 * which is the silent-undercount this whole feature exists to prevent. So an entry is now: a bullet,
 * or any line that is REFERENCE_SHAPED. Prose that names no source and carries no link is skipped,
 * and bold sub-headings are skipped rather than treated as terminators.
 */
function extractCitations(body: string): string[] {
  const lines = body.split("\n");
  const out: string[] = [];
  let inSources = false;
  for (const raw of lines) {
    if (/^#{1,6}\s/.test(raw)) {
      inSources = /^#{1,6}\s*(sources|references|further reading|bibliography)/i.test(raw);
      continue;
    }
    if (!inSources) continue;
    const line = raw.trim();
    if (!line || SUBHEADING.test(line)) continue;
    const bullet = line.match(/^[-*]\s+(.*\S)\s*$/);
    if (bullet) {
      out.push(bullet[1].trim());
    } else if (REFERENCE_SHAPED.test(line)) {
      out.push(line);
    }
  }
  return out;
}

function lit(s: string): string {
  return JSON.stringify(s);
}

async function main() {
  const url = resolveDbUrl(true);
  if (!url) {
    console.error("Set DATABASE_URL (or DATABASE_URL_UNPOOLED) in .env.local.");
    process.exit(1);
  }
  neonConfig.webSocketConstructor = ws;
  const pool = new Pool({ connectionString: url });
  const db = drizzle(pool, { schema });

  const courses = await db
    .select({ id: schema.courses.id, slug: schema.courses.slug, title: schema.courses.title })
    .from(schema.courses)
    .where(inArray(schema.courses.slug, STAGED_COURSES));

  // A slug can exist on more than one tenant. Citations are a property of the TEXT, not of the
  // tenant, so identical text on two tenants produces one entry: the key is derived from the text.
  // courses.slug is nullable in the schema, so narrow before using it as a map key.
  const bySlug = new Map<string, { id: string; slug: string; title: string }>();
  for (const c of courses) {
    if (!c.slug || bySlug.has(c.slug)) continue;
    bySlug.set(c.slug, { id: c.id, slug: c.slug, title: c.title });
  }

  const missing = STAGED_COURSES.filter((s) => !bySlug.has(s));
  if (missing.length) {
    console.warn(`! staged but not found in the database: ${missing.join(", ")}`);
    console.warn("  (seed them first, or drop them from STAGED_COURSES)");
  }

  const rows: string[] = [];
  const seen = new Set<string>();
  let totalCitations = 0;
  const perCourse: { slug: string; n: number; lessons: number }[] = [];

  for (const slug of STAGED_COURSES) {
    const course = bySlug.get(slug);
    if (!course) continue;
    const lessons = await db
      .select({
        slug: schema.lessons.slug,
        title: schema.lessons.title,
        text: schema.lessons.textContent,
      })
      .from(schema.lessons)
      .where(eq(schema.lessons.courseId, course.id))
      .orderBy(asc(schema.lessons.sortOrder));

    let n = 0;
    let lessonsWith = 0;
    for (const lesson of lessons) {
      const entries = extractCitations(lesson.text ?? "");
      if (entries.length) lessonsWith++;
      for (const entry of entries) {
        const key = keyFor(course.slug, entry);
        // The same source cited in five lessons is ONE thing to verify, not five.
        if (seen.has(key)) continue;
        seen.add(key);
        const urlMatch = entry.match(URL_RE);
        rows.push(
          `  {\n    key: ${lit(key)},\n    courseSlug: ${lit(course.slug)},\n    courseTitle: ${lit(course.title)},\n` +
            `    lessonSlug: ${lit(lesson.slug ?? "")},\n    lessonTitle: ${lit(lesson.title)},\n    text: ${lit(entry)},\n` +
            (urlMatch ? `    url: ${lit(urlMatch[1])},\n` : "") +
            `  },`,
        );
        n++;
      }
    }
    totalCitations += n;
    perCourse.push({ slug: course.slug, n, lessons: lessonsWith });
  }

  for (const p of perCourse) {
    console.log(`  ${p.slug.padEnd(34)} ${String(p.n).padStart(4)} citations across ${p.lessons} lessons`);
  }
  console.log(`\n${totalCitations} unique citation(s) from ${perCourse.length} staged course(s).`);

  if (process.argv.includes("--dry-run")) {
    console.log("(dry run, nothing written)");
    await pool.end();
    return;
  }

  mkdirSync(OUT_DIR, { recursive: true });
  const out =
    `// GENERATED by \`pnpm gen:citations\` from the lessons in the database, DO NOT EDIT BY HAND.\n` +
    `// Regenerate after editing any staged course's sources, then commit this file.\n` +
    `// The staging list and the types live in src/lib/citations.ts.\n\n` +
    `import type { Citation } from "@/lib/citations";\n\n` +
    `export const STAGED_CITATIONS: Citation[] = [\n${rows.join("\n")}\n];\n`;
  writeFileSync(join(OUT_DIR, "citations.ts"), out);
  console.log(`Wrote src/lib/citation-content/citations.ts`);
  await pool.end();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
