import type { Metadata } from "next";
import { requirePlatformOwner } from "@/lib/session";
import { DOWNLOAD_DOCS, downloadHref } from "@/lib/downloads";

export const metadata: Metadata = { title: "Downloads" };

// Owner-only list of the branded PDFs that can be handed to somebody outside the platform.
//
// These are generated at dev time by `pnpm gen:pdfs` from markdown in the gitignored plans/ tree and
// committed under public/downloads/, so this page is a plain index over a static registry: no
// runtime rendering, no DB read, nothing to go stale except the content itself.
export default async function DownloadsPage() {
  await requirePlatformOwner();

  return (
    <main className="mx-auto max-w-3xl px-4 py-10">
      <h1 className="text-3xl font-bold">Downloads</h1>
      <p className="mt-2 text-neutral-600 dark:text-neutral-400">
        Documents you can hand to somebody outside the platform. Every one carries the ecosystem mark,
        the app it came from, and the date it was revised, on <strong>every page</strong>, because a
        PDF travels and the page it came from does not travel with it.
      </p>

      <ul className="mt-8 space-y-4">
        {DOWNLOAD_DOCS.map((doc) => (
          <li
            key={doc.slug}
            className="rounded-lg border border-neutral-200 p-5 dark:border-neutral-800"
          >
            <div className="flex flex-wrap items-baseline justify-between gap-2">
              <h2 className="font-semibold">{doc.title}</h2>
              <span className="text-xs text-neutral-500">Revised {doc.revised}</span>
            </div>
            {doc.subtitle ? (
              <p className="mt-0.5 text-sm text-neutral-600 dark:text-neutral-400">{doc.subtitle}</p>
            ) : null}
            <p className="mt-2 text-sm text-neutral-700 dark:text-neutral-300">{doc.description}</p>
            <p className="mt-2 text-xs text-neutral-500">
              Written for: <strong>{doc.audience}</strong>
            </p>
            <div className="mt-4 flex flex-wrap items-center gap-3">
              <a
                href={downloadHref(doc)}
                download
                className="inline-flex min-h-11 items-center justify-center rounded-md px-4 text-sm font-semibold text-white"
                style={{ backgroundColor: "var(--accent)" }}
              >
                Download PDF
              </a>
              <a
                href={downloadHref(doc)}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex min-h-11 items-center justify-center rounded-md border border-neutral-300 px-4 text-sm font-medium dark:border-neutral-700"
              >
                Open in a new tab
              </a>
            </div>
          </li>
        ))}
      </ul>

      <p className="mt-8 text-xs text-neutral-500">
        Generated by <code>pnpm gen:pdfs</code> from markdown in <code>plans/</code>. That directory is
        gitignored, so the PDF is committed and served as a static file rather than rendered on
        request. To change a document: edit its markdown, re-run the command, commit the new PDF.
      </p>
    </main>
  );
}
