// GENERATED by `pnpm gen:future-work` from plans/future-courses/*.md (auto-discovered — add a .md, re-run, done) — DO NOT EDIT BY HAND.
// The source notes live in the gitignored `plans/` dir, so the content is committed here as
// plain strings: the deployed app imports this module and never reads the filesystem.

export interface ProposalDoc {
  /** Stable key: the filename without .md. Used as the /admin/future item key. */
  key: string;
  /** Human title: the doc's first `# heading`, else the de-slugged filename. */
  title: string;
  /** First real line of prose, for the card. */
  summary: string;
  body: string;
  provenance: string;
}

export const PROPOSAL_DOCS: ProposalDoc[] = [
  {
    key: "civics-more-proposal",
    title: "More civics courses — proposal (topic choice is BAM's to redirect)",
    summary: "Six high-value topics that fill gaps in the existing civics catalog (civics-101, us-constitution,",
    body: `# More civics courses — proposal (topic choice is BAM's to redirect)

Six high-value topics that fill gaps in the existing civics catalog (civics-101, us-constitution,
state-vs-federal, us-state-local-gov, how-to-run, help-a-campaign, spotting-misleading-marketing, +
50 states + DC). All would be non-partisan (process/institutions, no position on any bill/ruling).

## Drafted this session (shipped in \`bundle/content-courses-2026-07-09\`)
1. **How a Bill Becomes Law (Federal), in depth** — the existing civics-101 only covers it in a
   6-line overview; this is the full institutional process (committees, Rules Committee, filibuster/
   cloture/reconciliation, conference, veto/override).
2. **The Supreme Court & the Judicial Branch, in depth** — state-vs-federal uses cases to show the
   federalism split but never how the Court *operates*; this covers structure, cert, oral argument,
   opinions/precedent, interpretive approaches (neutrally), and checks on the judiciary.

## The 4 remaining candidates (not yet drafted — pick which to author next)
3. **The Bill of Rights / Know Your Rights (1st & 4th Amendment basics)** — a practical,
   plain-language walk through core rights (speech, religion, press, assembly; search/seizure) and
   what they do and don't cover. High everyday relevance; pairs with the civics + constitution courses.
4. **Voting & Elections 101** — how registration, primaries vs general, the Electoral College,
   ballot measures, and certification actually work. Non-partisan mechanics; complements the 50-state
   civics "how to take part" lessons with the national picture.
5. **Jury Duty & the Courts (the citizen's side)** — what a summons means, voir dire, grand vs petit
   juries, the trial process, and why jury service matters. A civic duty almost no course covers.
6. **Citizenship & Naturalization Basics** — who is a citizen, the naturalization process, the civics
   test, and the rights/responsibilities of citizenship. Useful for new-citizen and homeschool audiences.

**Recommendation:** #3 (Know Your Rights) and #4 (Voting & Elections 101) are the highest-leverage next
two — broadest everyday relevance and the most-requested civic-literacy gaps. #5 and #6 are strong
follow-ups. Tell Claude which to author.`,
    provenance: "plans/future-courses/civics-more-proposal.md",
  },
  {
    key: "history-of-unions",
    title: "History of unions",
    summary: "create a course on the history of history-of-unions",
    body: `create a course on the history of history-of-unions
in the US and abroad
create a track of courses that covers workers rights globally, with courses on different countries showing a diverse spectrum of how nations/states interact with labor`,
    provenance: "plans/future-courses/history-of-unions.md",
  },
  {
    key: "home-school-pricing-research",
    title: "Home-School Live BVC Pricing — Market Research (July 2026)",
    summary: "_Companion to `home-school-pricing.md` (the existing one-pager, tiers ~$20/$60/$150). This file is",
    body: `# Home-School Live BVC Pricing — Market Research (July 2026)

_Companion to \`home-school-pricing.md\` (the existing one-pager, tiers ~$20/$60/$150). This file is
the evidence base for that pager's numbers. Local research note — not for publication._

---

## 1. Comparables table

| Offering | What you get | Price | Per-unit basis | Source |
|---|---|---|---|---|
| **Outschool — group live class (guideline rate)** | Teacher-set live class, any format except 1:1 | **$17–21** per learner per hour (one-time/ongoing/short-course bands all cluster here; semester 8+ wk programs $18–20) | per student, per class-hour | [teach.outschool.com/insights/pricing](https://teach.outschool.com/insights/pricing/) |
| **Outschool — 1:1 tutoring (guideline rate)** | Private live tutoring | **$45–60/hr** (≤30 min sessions run $60–64/hr) | per student, per hour | [teach.outschool.com/insights/pricing](https://teach.outschool.com/insights/pricing/) |
| **Outschool — monthly membership (buyer side)** | Credit bundle a parent buys, spent on live/self-paced classes | **$40/mo** (~1 live class/wk) · $70/mo (~2/wk) · $120/mo (~3/wk) · $240/mo (~4/wk) | per student, per month | [brighterly.com/blog/outschool-pricing](https://brighterly.com/blog/outschool-pricing/) |
| **Outschool — 1:1 tutoring (market/actual)** | Private tutoring, promo-inclusive | $15–118 per lesson (national comparison: $25–80/hr) | per lesson | [brighterly.com/blog/outschool-pricing](https://brighterly.com/blog/outschool-pricing/) |
| **Prenda microschool — direct-pay** | Platform fee + a "guide" (facilitator) fee, full weekday microschool, not a single subject | **$219.90/mo** platform fee alone; guide fee typically $3,500–4,000/yr (~$290–333/mo) → **~$475–517/mo total** per student | per student, per month | [help.prenda.com — Financial Policies](https://help.prenda.com/knowledge/prenda-financial-policies-direct-pay-microschools) |
| **Primer microschool** | Full micro-private-school seat; heavily state-scholarship-funded | **$0–$3,200/yr** out-of-pocket depending on state/income (many families pay $0 via ESA/scholarship) | per student, per year | [primer.com/tuition](https://primer.com/tuition) |
| **Sora Schools** (full-time accredited online private school, grades 6–12 — ceiling reference, not a single-subject comparable) | Full course load, not enrichment | **$17,900/yr** full tuition; flexible-tuition band **$7,500–$16,000/yr** | per student, per year | [soraschools.com/tuition-and-affordability](https://soraschools.com/tuition-and-affordability) |
| **Small-group / online tutoring, general market** | Live tutoring, subject-dependent | **$20–60/hr** online average; by grade: K-2 $25–45, 3-5 $30–55, 6-8 $40–65, 9-12 $50–100/hr | per student, per hour | [brighterly.com/blog/tutoring-rates-per-hour](https://brighterly.com/blog/tutoring-rates-per-hour/) |
| **Homeschool co-op membership (typical)** | Parent-taught or paid-instructor classes, in-person hub | **$500–$3,000+/yr** all-in tuition; separately, registration $25–150/family, semester fee $70–140, building fee $125–350 | per family (+ per-class add-ons) | [numaschool.com — co-op fees](https://numaschool.com/learn/glossary/co-op-membership-fees), [tshanywhere.org — co-op tuition guide](https://www.tshanywhere.org/post/co-op-homeschool-tuition-fees-guide) |
| **Real 2026-27 co-op examples** | Registration/membership only (classes billed separately) | Joy Homeschool Co-op **$115/family**; TEACH (Tri-Cities) **$45/family**; Ignite Homeschool Co-op **$150/student** (2026-27) | per family or per student | [joyhomeschool.org](https://www.joyhomeschool.org/), [teachtricities.com](https://www.teachtricities.com/tn/teach/index.cfm), [ignitehomeschoolcoop.org](https://www.ignitehomeschoolcoop.org/registration/fees-tuition) |
| **Maven** (adult cohort-based courses — ceiling reference for "live cohort" premium, not a kids' comparable) | Multi-week live cohort with expert instructor, projects, community | **$500–$3,000/cohort** (avg ~$500; typical band $800–$2,500) | per person, per cohort/course | [maven.com/resources/course-price-and-length](https://maven.com/resources/course-price-and-length), [help.maven.com — pricing your course](https://help.maven.com/en/articles/6732396-pricing-your-course) |
| **Woke Homeschooling** (Black-history-adjacent, self-paced only — no live component) | Downloadable U.S.-history curriculum | Grades 3–7: **$50**; high-school (2 parts): **$60 each** — one-time purchase, not recurring | per curriculum, one-time | [wokehomeschooling.com](https://wokehomeschooling.com/) |
| **Gilder Lehrman Institute — self-paced African American History courses** | Lecture-based self-paced course w/ primary sources, quizzes | **$29.99** (affiliate-school network) / **$39.99** (general public) | per course, one-time | [gilderlehrman.org — self-paced courses](https://www.gilderlehrman.org/history-resources/curriculum/3-self-paced-courses-african-american-history) |
| **Cultural Roots Homeschool Co-Op** (Richmond, VA — culturally centered, closest live positioning to BVC) | Weekly à la carte classes centered on Black/Brown/Indigenous history & culture | **No public price found** — site frames participation via tax-deductible "Patron" donations, not a listed tuition/class fee | unknown | [culturalrootsco-op.com](https://culturalrootsco-op.com/) — **could not source a hard number** |
| **National Black Home Educators (NBHE)** | Support/resource network, co-op-formation help | No live-class pricing published (membership/resource-network model) | n/a | [nbhe.net](https://www.nbhe.net/) — **could not source a hard number** |

---

## 2. Synthesis — going rate by delivery model

**(a) Async/recorded access only.** There's no clean like-for-like: Outschool doesn't sell a pure
self-paced subscription, and the closest culturally-specific analogs (Woke Homeschooling, Gilder
Lehrman) are **one-time** purchases at **$30–$60**, not recurring. The nearest recurring proxy is a
co-op's per-family registration/semester fee amortized monthly (~$10–30/mo-equivalent). A recurring
$20–25/mo for ongoing access + quizzes + certificate + a monthly live group Q&A is defensible and, if
anything, priced conservatively against Outschool's cheapest bundle ($40/mo, which already includes
one weekly *live* class).

**(b) Weekly live group class.** Outschool's own guideline rate ($17–21/learner/hr) implies **~$68–84/
month** for one weekly 1-hour class billed à la carte; Outschool's packaged membership compresses
that to $40–70/mo because popular repeat classes are discounted inside the credit system. So the
real-world range for "weekly live group class" is **$60–90/month per student**, with $60–70/mo as the
most common lived price once bundled.

**(c) Live + small-group + parent reporting/light 1:1.** This sits between a large-group live class
and true 1:1 tutoring. Small-group tutoring commands a discount off solo rates (one source cites
~70% lower cost than 1:1 for similar gains) but is still meaningfully above a big-group class —
figure **$100–200/month** per student for a weekly small-group session, before adding the reporting
layer. Full 1:1 tutoring ($45–118/hr) and full-time microschool tuition ($475–1,500+/mo) sit well
above this and confirm there's plenty of headroom — a $150/mo "guided" tier is nowhere near the
ceiling this market will bear.

**Ceiling reference:** Families who've already looked at Prenda (~$475–517/mo), Sora ($1,492/mo
equivalent), or private tutoring ($45+/hr) will not blink at $150/mo for one subject's live +
guided offering — it reads as a small fraction of a full alternative-schooling budget.

---

## 3. Recommended 3 tiers for BVC home-school

All tiers priced **per student, per month** (matches Outschool's dominant convention and avoids the
per-family ambiguity co-ops have — see risk note below). Season equivalents assume a ~10–12-week
Season 1 run.

| | **Explorer (Low)** | **Cohort (Mid) — ⭐ ANCHOR** | **Guided (High)** |
|---|---|---|---|
| **Price** | **$20–25/student/mo** | **$60/student/mo** (~$150–180/season) | **$150/student/mo** (~$750/season) |
| **Positioned against** | Priced under Outschool's cheapest live bundle ($40/mo); above one-time self-paced curricula ($30–60) because it's recurring + monthly live | Sits exactly inside the Outschool weekly-live-class real-world range ($60–90/mo) | Below small-group-tutoring-plus-reporting ($100–200+/mo) and far below 1:1 tutoring or microschool tuition |
| **What's included** | Self-paced Season 1 course + Commodity Map; quizzes + certificate; **monthly** live group Q&A | Everything in Explorer + **weekly** live class (cohort-sized group) via \`/live\`; quick-check assignments | Everything in Cohort + **weekly small-group live** (capped roster) + full capstone project with feedback + parent progress reports (attendance/grades via the upcoming Family view) |
| **What Learn.WitUS already delivers** | Recorded course, quizzes, certificate | + cohorts, \`/live\` | + \`/live\` small-group cap, + Family view (in progress) is the differentiator no comparable at this price offers |

**Anchor the Mid tier.** $60/mo is the best-evidenced number in this set — it's not an estimate, it's
where Outschool's own guideline rate and its packaged membership price converge. Lead pricing
conversations with Cohort, then show Explorer as "try it first" and Guided as "if you want feedback
and reporting."

---

## 4. Validation note

**Ask the parent:**
1. *"How many kids total (your child + classmates), and would a per-child monthly price work, or
   would you rather I quote one flat price for the whole group?"* — tests per-student vs. per-family
   pricing tolerance and locks the group size before quoting.
2. *"What have you paid (or budgeted) for a comparable class — an Outschool course, a co-op class, or
   a tutor — for a similar subject?"* — anchors to her actual revealed willingness-to-pay instead of
   market averages, and surfaces whether she's benchmarking against $40/mo Outschool bundles (cohort
   tier will look pricier) or $500–3,000/yr co-op tuition (cohort tier will look cheap).

**Pricing risks:**
- **Per-family vs. per-child.** Co-ops mostly price per-family; Outschool prices per-child. If the
  "classmates" are a fixed small group (not open enrollment), a flat group rate (e.g., "$X/week for
  up to 6 kids") may land better than strict per-seat pricing — decide before quoting.
- **Sibling / group discount.** Comparable co-ops routinely stack registration + semester + per-class
  fees; a simple 10–15% discount for 3+ students from one family (or one classmate group) is
  standard practice and should be pre-built into the quote, not negotiated ad hoc.
- **Free trial.** Outschool gives new users 40 free credits (~1 class); co-ops often waive the first
  session. A free first live session lowers the parent's risk and matches category norms.
- **Anchoring mismatch.** If she's already compared BVC to Outschool's $40/mo entry tier rather than
  the $60–90/mo real weekly-live rate, the Cohort tier may need the "here's what a weekly live class
  actually costs elsewhere" framing from §2(b) above.

---

## 5. Verdict on the existing $20 / $60 / $150 one-pager

| Tier | Existing price | Evidence says | Recommendation |
|---|---|---|---|
| **Explorer** | ~$20/mo | Slightly under Outschool's cheapest live bundle ($40/mo) and in line with amortized co-op registration fees; no direct pure-async comparable to test against | **Keep, or nudge to $25/mo.** Evidence does not support lowering. |
| **Cohort** | ~$60/mo (~$150/season) | Matches the real-world weekly-live-class range ($60–90/mo) almost exactly | **Keep as-is — this is the best-supported number in the set.** |
| **Guided** | ~$150/mo (~$750/season) | Below the $100–200+/mo small-group-plus-reporting comparable band's upper end, and far below 1:1 tutoring/microschool ceilings | **Keep. There is headroom to test higher ($175–200/mo) if the parent reporting/Family-view feature lands as a strong differentiator, but $150 is defensible today.** |

---

## Numbers I could NOT source (flagged, not invented)

- **Cultural Roots Homeschool Co-Op** (Richmond, VA) — the single closest live, culturally-centered
  comparable to BVC — publishes no tuition/class price; site framing is donation/"Patron"-based.
- **National Black Home Educators** — resource/support network, no live-class pricing model found.
- **Outschool actual realized multi-week-course total price** — only the per-hour guideline rate and
  a rough illustrative example ($50 for a 4-week series) were found; Outschool doesn't publish an
  aggregate average because every teacher sets their own price.
- **Sora Schools single-subject/enrichment add-on pricing** — only full-enrollment annual tuition was
  found; no per-course or drop-in rate.`,
    provenance: "plans/future-courses/home-school-pricing-research.md",
  },
  {
    key: "home-school-pricing",
    title: "Live BVC Classes for Homeschoolers — one-pager",
    summary: "_Send-ready draft. Also as a print-to-PDF page: `home-school-pricing.html` (open → Cmd/Ctrl-P → Save as PDF)._",
    body: `# Live BVC Classes for Homeschoolers — one-pager

_Send-ready draft. Also as a print-to-PDF page: \`home-school-pricing.html\` (open → Cmd/Ctrl-P → Save as PDF)._

---

## Live Better Vice Club, taught by Brand Anthony McDonald
**On Learn.WitUS.Online — cited, media-rich lessons + a live class with the instructor.**

Your student joins **Better Vice Club: Season 1** — the story of how everyday commodities (coffee, tea,
chocolate, sugar, and more) shaped world history, geography, and culture — on an interactive **Commodity
Map**. Self-paced lessons at home, plus **live sessions** with me for discussion, questions, and projects.

**How it works:** each student gets a free login, enrolls in the class, works through the lessons at home,
and joins the scheduled **live class** (video + Q&A). Progress, quizzes, and a certificate are built in.

---

### Three ways to join

| | **Explorer** | **Cohort** ⭐ | **Guided** |
|---|---|---|---|
| **Best for** | Independent learners | A homeschool class/co-op | Students who want feedback |
| **Self-paced Season-1 course + map** | ✓ | ✓ | ✓ |
| **Live class with the instructor** | Monthly group Q&A | **Weekly live class** | **Weekly small-group live** |
| **Quizzes + certificate** | ✓ | ✓ | ✓ |
| **Graded assignments / project feedback** | — | Quick-check | **Full capstone + feedback** |
| **Parent progress dashboard** (grades + attendance) | — | — | ✓ |
| **Price (per student)** | **$20/mo** | **$60/mo** _(or $150/season)_ | **$150/mo** _(or $750/season)_ |

_**First live session is free.** **Sibling/classmate discount:** 10–15% off for 3+ students from one
family or group. Larger co-ops (5+): ask about a group rate._

---

### Why families like it
- **Cited & honest** — every claim ties to a real source (APA), so it meets homeschool-portfolio standards.
- **One story, many subjects** — history, geography, economics, and culture in one thread.
- **Interactive** — the Commodity Map lets kids explore where each story begins.
- **A real teacher** — live time with the instructor, not just videos.

### Getting started
1. I set up your class group and send each student a login.
2. Students enroll and start Season 1 at their own pace.
3. We hold the first live session and set a weekly time.

**Contact:** _[your email / booking link]_ · **Learn.WitUS.Online**

---

_Notes (internal): pricing validated against 2026 comparables (\`home-school-pricing-research.md\`) —
Outschool live ~$17–21/learner-hr & $40–240/mo bundles, co-ops $45–150/family, microschools as the
ceiling. **$60 Cohort is the best-anchored tier** (matches the real weekly-live rate); Guided has
headroom to test $175–200. Live now runs **in-app**: the app hosts the course, Commodity Map,
**live class + live chat + "who's here" roster**, recordings (ViLoud embed), quizzes, certificates,
and the **parent Family view** (a linked parent sees their own child's progress, grades, and
attendance — powers the Guided tier's progress dashboard). Kid-friendly avatar+PIN login is available
for young students without email._`,
    provenance: "plans/future-courses/home-school-pricing.md",
  },
  {
    key: "travel-abroad-proposal",
    title: "Travel & Living Abroad — course track proposal (from the US)",
    summary: "A new \"Travel & Living Abroad\" category. Two courses are building now; the rest are proposals —",
    body: `# Travel & Living Abroad — course track proposal (from the US)

A new **"Travel & Living Abroad"** category. Two courses are building now; the rest are proposals —
pick which to author. All cited from authoritative gov sources (travel.state.gov, CDC, CBP, IRS,
USCIS, SSA), all stressing "verify current rules/fees at the official source" since these change.

## Building now
1. **How to Get a U.S. Passport** — book vs. **card** (dedicated section: card is land/sea only, NOT
   international air), first-time (DS-11) vs. renewal (DS-82), documents, fees, expedited, minors,
   lost/stolen, the 6-month-validity rule. _(travel.state.gov)_
2. **Travel Visas 101** — how to figure out and get a visa for any destination as a US traveler:
   visa-free / visa-on-arrival / e-visa / embassy, Schengen + **ETIAS**, documents, a repeatable
   research checklist. _(travel.state.gov country pages, EU/ETIAS, embassy sites)_

## Proposed — Short trips & tourism (traveling FROM the US)
3. **International Travel Basics** — the whole pre-trip checklist tying passport + visa + insurance +
   health + money + **STEP enrollment** (Smart Traveler) + itinerary together. The "start here" hub.
4. **Travel Health & Safety** — CDC destination vaccines & health notices, travel insurance, staying
   safe, what to do in an emergency abroad (embassy/consulate help). _(CDC Travelers' Health, State Dept)_
5. **Money Abroad** — currency, cards vs. cash, foreign-transaction & ATM fees, avoiding scams,
   notifying your bank. _(CFPB, FTC)_
6. **Flying Internationally & Coming Home** — airports/customs, **CBP re-entry**, **Global Entry /
   TSA PreCheck / Trusted Traveler**, and **what you can (and can't) bring back** (duty, ag/food rules).
   _(CBP, TSA)_
7. **Culture & Language Ready** — cultural etiquette, basic language prep, respectful travel. (Pairs
   with the existing Languages atlas + language courses.)

## Proposed — Moving & living abroad (long-term)
8. **Moving Abroad 101** — the big decisions: tourist stay vs. **residency** vs. citizenship, types of
   long-stay/retirement/work visas, choosing a country, the realistic timeline & costs. The hub course.
9. **Working Abroad & Digital-Nomad Visas** — work permits, employer sponsorship, the wave of
   **remote-work/digital-nomad visas**, and what they do/don't allow.
10. **Taxes for Americans Abroad** — the big one: the US taxes citizens on **worldwide income** even
    abroad. Covers the **Foreign Earned Income Exclusion**, **FBAR**, **FATCA**, foreign tax credit,
    filing deadlines. High-value, high-anxiety topic. _(IRS — cite carefully; "consult a tax pro.")_
11. **Banking & Money When You Live Abroad** — how **FATCA** affects opening foreign accounts,
    keeping US accounts, transferring money, currency risk. _(IRS/Treasury, CFPB)_
12. **Healthcare Abroad** — international/expat health insurance, how care differs, Medicare doesn't
    travel, planning for prescriptions & emergencies.
13. **Retiring Abroad** — **Social Security payments while overseas** (SSA), residency/retirement
    visas, taxes + healthcare for retirees, cost-of-living. _(SSA, State Dept)_
14. **Studying Abroad** — programs, student visas, safety, credit transfer, funding.
15. **Dual Citizenship & Renunciation basics** — what dual citizenship is, how the US treats it, and
    the (rare, serious) renunciation process. _(State Dept)_
16. **Shipping & Logistics of an International Move** — movers vs. ship-it-yourself, customs on your
    goods, pets, what to sell/store, mail forwarding & voting from abroad.

## Recommended sequencing
- **Now:** Passport + Visas (building).
- **Next (short-trip pillar):** #3 International Travel Basics (the hub) + #6 Flying & Coming Home
  (Global Entry / customs) — highest everyday demand.
- **Then (moving pillar):** #8 Moving Abroad 101 (hub) + #10 Taxes for Americans Abroad (the topic
  people most fear getting wrong).
- The rest as demand shows.

## Note
The tax/legal/immigration courses must be firmly framed as **educational, not professional advice**
(the new site-wide disclaimer already covers this) and point to IRS/USCIS/a licensed professional.`,
    provenance: "plans/future-courses/travel-abroad-proposal.md",
  },
  {
    key: "workers-rights-track-proposal",
    title: "Workers' Rights Around the World — course track proposal",
    summary: "A proposed \"Workers' Rights\" track: one built anchor course plus a set of country courses chosen",
    body: `# Workers' Rights Around the World — course track proposal

A proposed **"Workers' Rights"** track: one built anchor course plus a set of country courses chosen
to span a genuinely diverse spectrum of how states interact with labor — not a tour of rich
democracies. From BAM's note (\`plans/future-courses/history-of-unions.md\`):

> "create a track of courses that covers workers rights globally, with courses on different countries
> showing a diverse spectrum of how nations/states interact with labor"

**Nothing below is built.** These are proposals — pick which to author, and in what order.

---

## The anchor (built, \`content/history-of-unions\`)

**The History of Unions: America and the World** (Culture & History) — 7 sections, 22 teaching
lessons, 7 quizzes, 1 exercise. The full US arc (Knights/AFL → Haymarket → Homestead/Pullman →
Triangle → Wagner Act → CIO → Taft-Hartley → Randolph/Memphis → PATCO → the BLS density series),
told with the parts a comfortable course skips (the NLRA's agricultural/domestic carve-out, unions'
own record of racial and gender exclusion, the corruption chapters). Then one lesson each on six
national models, and the ILO.

**The anchor's real payload is a reusable analytical spine — "the four questions."** Every course in
this track should use it as its skeleton, so the track compounds instead of being twelve unrelated
country tours:

1. **Who is allowed to organise?**
2. **Who is excluded?**
3. **Who bargains with whom, and at what level?**
4. **What happens to you if you try?**

A student who has done the anchor plus any three country courses should be able to walk into a
country they have never studied and produce a defensible first-pass answer to all four.

A companion course, **Know Your Rights at Work** (\`content/know-your-rights-at-work\`, parallel
branch), covers *your rights on the job today*. The anchor cross-links to it; the country courses
should too. The division of labour is: **that one = what do I do on Monday. This track = how did
this get built, and why is it different over there.**

---

## Selection criteria (why these countries, and not others)

A country earns a slot only if it teaches something **no other course in the track can teach**. The
test is not "is it important" — it is "does removing it leave a hole in the spectrum."

The spectrum this track is trying to cover, end to end:

| Position on the spectrum | Country that anchors it |
|---|---|
| Workers **in the boardroom**, by statute | Germany |
| Unions run the **welfare plumbing**; the wage floor is a contract, not a law | Sweden / Denmark |
| The union as **liberation movement** — and then as part of the government | South Africa |
| The union as the thing that **brought down the state** | Poland |
| Most workers have **no employer at all** to bargain with | India |
| Unions **chartered and funded by the state** — and then defunded overnight | Brazil |
| The union as a **tool of the employer** (the protection contract) — and rights enforced through a **trade deal** | Mexico |
| A labor system **deliberately engineered to atomise bargaining** | Chile |
| Rights won *with* democracy — and then policed with **damages suits against individual strikers** | South Korea |
| Your real employer is a **brand on another continent** | Bangladesh |
| The union **is an arm of the party-state** | China |
| Workers with **almost no rights at all** | The Gulf (Qatar / UAE / Saudi Arabia) |

Two deliberate omissions, so the reasoning is on the record:

- **The UK.** Voluntarism, the 1984–85 miners' strike, the 2016 Trade Union Act, the 2023
  minimum-service-levels law. Genuinely interesting, but it overlaps the US course heavily (common
  law, adversarial, declining density) and would spend a slot without widening the spectrum. **Build
  it only if a UK audience materialises.**
- **France.** The very low density / very high coverage gap is the most vivid illustration of
  Question 3 anywhere on earth — but it is *already* the punchline of the Germany course, and
  France's own union landscape (multiple competing confederations, extension by ministerial decree)
  is more confusing than instructive for a first pass. **Fold the France contrast into Germany;
  don't build the course.**

---

## Wave 1 — build first (highest teaching value per unit of sourcing pain)

These four are the backbone. Each is well-sourced from official/primary material, each anchors a
distinct end of the spectrum, and none requires a subject-matter reviewer to ship responsibly.

### 1. Germany — *Workers on the Board*
**Teaches uniquely:** that a country can have roughly the same union **membership** rate as the US
(14.1%, 2024) and roughly **five times** the bargaining **coverage** (~49–50%) — and that the
difference is a design choice, not a cultural one. Board-level co-determination (Co-determination
Act 1976: half the supervisory board of a >2,000-employee company) and the **dual channel** (works
councils are statutory bodies elected by *all* employees, and are not the union).
**Why it earns a slot:** it is the strongest available refutation of "unions vs. companies" as the
only possible frame. Nothing else in the track shows workers with a structural, permanent, legal
seat.
**Hard parts:** the two-tier board is genuinely confusing to an American student — this course needs
real diagrams. And the honest version must include the **casting-vote catch** (parity of seats, not
of power) and the insider/outsider critique (co-determination is argued to protect permanent staff
at the expense of everyone else). Sourcing is excellent: statutes in English at
\`gesetze-im-internet.de\`, ETUI's \`worker-participation.eu\`, Hans-Böckler-Stiftung, OECD/AIAS.

### 2. Sweden & Denmark — *The Wage Floor That Isn't a Law*
**Teaches uniquely:** the **Ghent system** (unemployment insurance administered by union-affiliated
funds → density around 65%), **sectoral bargaining**, and the fact that neither country has a
statutory national minimum wage — because the floor is a contract. Plus Danish **flexicurity**: easy
dismissal, generous benefit, active retraining — a bargain most Americans have never heard proposed.
**Why it earns a slot:** it detonates the assumption that a legal protection must be a *law*. It also
teaches the track's best methodological habit — *look for the plumbing before you reach for the
culture*.
**Hard parts:** it must tell the **erosion** story (private unemployment funds that don't require
membership; decades of decline from a higher peak; pressure from the EU Adequate Minimum Wages
Directive 2022/2041) or it is a tourism brochure. Also: Sweden and Denmark differ enough that the
course has to teach both, not blur them into "Scandinavia."

### 3. Poland — *Solidarność: When a Union Brought Down a State*
**Teaches uniquely:** that in a one-party state, "who may organise?" **is** "who governs?" The 21
Demands (demand #1 was the right to form free unions, not pay), the Gdańsk Agreement (31 Aug 1980),
roughly 10 million members, martial law (13 Dec 1981), the Round Table, June 1989.
**Why it earns a slot:** it is the most dramatic and most *teachable* proof of the anchor's thesis,
and it puts a trade union at the centre of the biggest geopolitical story of the late 20th century —
which most students have never been told.
**Hard parts:** **the present tense is a minefield.** The 1980–89 history is superbly sourced (UNESCO
Memory of the World holds the 21 Demands; the European Solidarity Centre in Gdańsk has a vast open
archive; the Institute of National Remembrance). But today's NSZZ "Solidarność" is a politically
aligned organization very different from the 1980 movement, and **Lech Wałęsa's own record is
fiercely contested in Polish politics**, including long-running allegations about a 1970s
security-service file. **Recommendation: build the course on 1980–89, state explicitly that the
movement's contemporary legacy is contested in Poland today, and do not adjudicate Wałęsa's file.**
Say so in the course, in one honest paragraph. That is the whole fix.

### 4. Mexico — *The Protection Contract, and the Trade Deal That Came for It*
**Teaches uniquely:** a **third kind of union object** the anchor only gestures at — the union that
is a **tool of the employer**. Mexico's "protection contracts" were collective agreements signed
between a company and a friendly or phantom union, sometimes before a single worker was hired, which
then legally blocked any real union from organising. Then: the **2019 labour reform** (personal,
free, direct, secret votes to legitimise existing contracts) and the **USMCA Rapid Response Labor
Mechanism** (in force 2020), under which the United States can impose tariffs **on one specific
factory** for denying freedom of association.
**Why it earns a slot:** the RRM is the only concrete, working, *enforceable* international labor
mechanism in the whole track — the answer to the anchor's bleak ILO lesson ("the floor is made of
paper"). And the protection contract teaches a student to ask *whose union is it?* rather than *is
there a union?*
**Hard parts:** none that are severe. Sourcing is good and public: the Ley Federal del Trabajo as
amended (2019), the USMCA text, and USTR's **published list of RRM cases** — which is a gift,
because students can read the actual disputes. Keep it neutral on US–Mexico trade politics; teach
the mechanism, not the trade war.

---

## Wave 2 — build second (widens the spectrum; needs more care)

### 5. India — *When Most Workers Have No Employer*
**Teaches uniquely — and this may be the single most important course in the track.** The
overwhelming majority of India's workforce is **informal**: no contract, no employer of record,
frequently no identifiable legal employer at all. Every concept in the anchor course — the election,
the contract, the grievance procedure, the duty to bargain — assumes an *employer*. **India is where
that assumption breaks.** It teaches SEWA (the Self-Employed Women's Association, founded 1972) — a
union of self-employed women, which is a genuinely different institutional invention — and general
strikes that mobilise tens of millions.
**Why it earns a slot:** it is the course that stops a student from thinking "worker = employee." It
is also, bluntly, the world's largest workforce, and its absence from the track would be
embarrassing.
**Hard parts:** **the statistics are genuinely contested** — informality is defined differently by
different bodies and the headline percentage swings accordingly. The course must name its definition
and its source rather than quoting a number. The 2019–20 **Labour Codes** (consolidating dozens of
statutes) are politically contested and their implementation has been staggered — do not state their
status as settled; date it. Sources: ILO India, the Periodic Labour Force Survey, the Codes' text on
\`india.gov.in\`, SEWA's own materials.

### 6. South Korea — *Democracy, the Chaebol, and the Lawsuit as a Weapon*
**Teaches uniquely:** rights won *alongside* democracy (the 1987 Great Workers' Struggle), the
**regular/irregular dual labour market** inside the chaebol conglomerates, and a repression mechanism
students will not have seen anywhere else — **civil damages suits and provisional seizure of assets
brought against individual strikers**, which can financially destroy a worker without ever
criminalising the strike. Great hook: **Korea ratified ILO Conventions 87 and 98 only in 2021** — a
rich, democratic OECD member that took until the 2020s to sign the freedom-of-association floor.
**Why it earns a slot:** it is the track's sharpest version of **Question 4** *inside a wealthy
democracy*, which is exactly where American students assume Question 4 is boring.
**Hard parts:** contested domestic politics (the "yellow envelope" bill limiting damages suits has
been passed, vetoed and re-fought — date any claim about its status). Sourcing is otherwise good:
ILO NORMLEX, OECD, the KCTU and FKTU, Korean labour statutes.

### 7. Brazil — *State-Chartered Unions, a Union-Made President, and the 2017 Rupture*
**Teaches uniquely:** **corporatism** — a system in which unions are chartered by the state, granted
monopoly representation of a category in a territory, and funded by a **compulsory union tax**
deducted from workers whether or not they joined (the 1943 CLT structure). Then the "new unionism"
of the ABC metalworkers, which produced a president. Then **Law 13.467/2017**, which abolished the
compulsory tax and cut union finances off at the knees more or less overnight. Also: Brazil has a
dedicated **labour judiciary**, which almost no student has ever heard of.
**Why it earns a slot:** it is a controlled experiment nobody could have designed. *What happens to
unions that were funded by the state, when the state stops funding them?* Brazil answers it.
**Hard parts:** **political heat.** Lula is a current/recent head of state and Brazilian politics is
brutally polarised. The course must be scrupulously neutral, stick to the statute and the numbers,
and date everything. Sourcing is fine (CLT, Law 13.467/2017, ILO, IBGE).

### 8. Chile — *A Labor System Designed to Be Weak*
**Teaches uniquely:** the **1979 Plan Laboral** — a labour code written under a military dictatorship
which deliberately **fragmented bargaining to the individual firm**, permitted competing unions
inside one workplace, and constrained the right to strike. This is the clearest documented case
anywhere of a labour system *engineered*, on purpose, to atomise worker power — and it survived the
return to democracy largely intact, which is the more interesting half of the story.
**Why it earns a slot:** every other course shows institutions that *evolved*. Chile shows one that
was **designed**, by named people, with a stated goal. It turns Question 3 from a description into an
accusation — and it is the perfect final lesson before a student re-reads their own country's law.
**Hard parts:** Pinochet-era history is contested and painful; the course must handle the
dictatorship soberly and cite carefully. Sourcing is adequate (the Código del Trabajo, ILO, OECD,
Chilean scholarship) but much of the best material is in Spanish — a translation pass is required.

---

## Wave 3 — build last (hardest to source; the state may be hostile)

These three complete the spectrum and are the ones the track *needs* in order not to be a tour of
comfortable countries. They are also the ones most likely to produce a credibility failure if built
carelessly. **Do not build these until the method is proven on Waves 1–2.**

### 9. China — *The Union That Is the State*
**Teaches uniquely:** the sharpest possible form of **Question 1**. The ACFTU is the world's largest
union organization and a genuinely different *object*: unions operate under Party leadership by
statute, a workplace union must affiliate upward, and forming one requires higher-level approval. The
right to strike was in the 1975 and 1978 constitutions and was **removed in 1982**.
**Why it earns a slot:** without it, "union" reads as a fixed unit across countries. It isn't.
**What makes it hard — and this is a *specific* difficulty worth understanding:** the **law is easy**
and the **practice is hard**. The statutes are public and officially translated (\`npc.gov.cn\`), so
the legal structure is unarguable and can be taught from primary sources with total confidence. What
cannot be sourced cleanly is *what actually happens*: strike frequency, detentions of labour NGO
staff, conditions. The standard open dataset was **China Labour Bulletin's strike map**, and CLB — a
Hong Kong-based advocacy organization — **wound down its operations in 2023**, which leaves a real
and worsening evidence gap. The state is hostile to independent research on exactly this question.
**What BAM would need:** a hard editorial rule — *build the course from the statute and from ILO
supervisory-body findings; state explicitly what cannot be verified; do not launder advocacy claims
as fact; do not caricature (the ACFTU does administer real welfare and legal aid); date everything.*
Done that way this course is defensible and genuinely excellent. Done the other way it is a
liability.

### 10. The Gulf — *Kafala: The Workers Who Build the Cities* (Qatar / UAE / Saudi Arabia)
**Teaches uniquely:** the near-zero end of the spectrum, and the exact same *mechanism* as the NLRA's
1935 farm/domestic carve-out — a class of worker defined **by law** as outside the protections
everyone else gets, doing the hardest and most dangerous work. Qatar's 2020 reforms (Law No. 17,
minimum wage; Law No. 19, removing the No-Objection Certificate) are **real** and must be taught as
real; and migrant workers still **may not form or join trade unions**, which must also be taught.
**Why it earns a slot:** because a workers'-rights track that stops at countries with unions has not
described the world.
**What makes it hard:** the two failure modes are the promotional version (recite the 2020 laws,
stop) and the atrocity version (recite abuses, ignore that the law changed). **Both are propaganda.**
Independent research access is limited, official statistics are thin, and *every* available source —
including the ILO's own Qatar office, which operates inside a formal joint programme with the
government and is therefore both authoritative and diplomatically constrained — is motivated.
Migrant-worker death-toll figures in particular are contested and have been misreported by major
outlets.
**What BAM would need:** a rule that **every claim carries the statute + the ILO + at least one
independent monitor**, that contested figures are presented *as contested, with the range and the
dispute named*, and that nothing is asserted undated. Also: do not erase migrant workers' agency —
wildcat strikes happen and are documented.

### 11. Bangladesh — *Rana Plaza and the Brand on Another Continent*
**Teaches uniquely:** what Question 3 means when **your real employer is a logo in another country**.
The Rana Plaza collapse (24 April 2013; more than 1,100 garment workers killed) and what followed:
the **Accord on Fire and Building Safety in Bangladesh** — a *legally binding* agreement between
global brands and global unions, enforceable through arbitration. That is one of the most important
labour-governance experiments of this century and it is essentially invisible to American students,
who are wearing its output.
**Why it earns a slot:** it is the course with the shortest distance between the syllabus and the
student's own shirt. It also answers the ILO lesson's despair with something that actually binds —
not a treaty, but a contract.
**What makes it hard:** the **Bangladeshi state has been hostile to garment-union organising** —
union registration is difficult, and organisers have been dismissed, blacklisted and assaulted (well
documented). The Accord's status has been repeatedly renegotiated and litigated, so any claim about
its current form must be dated. Sourcing is otherwise good: ILO, Better Work, the Accord's own
published inspection reports, the brands' own disclosures.

---

## Optional / later

- **Nigeria (or Kenya)** — African labour *outside* South Africa. The Nigeria Labour Congress
  repeatedly calls general strikes that shut the country (fuel-subsidy disputes), so a union
  federation functions as de facto political opposition — a thing American students never see.
  Sourcing is moderate; informal-sector statistics are weak. Good candidate if the track continues.
- **The UK** and **France** — see "deliberate omissions" above.
- **South Africa** is listed in the spectrum table and *should* be built — see the reviewer caveat in
  "What BAM would need." It sits between Wave 1 and Wave 2 on difficulty: the archives are excellent
  (South African History Online, the O'Malley/Nelson Mandela Foundation archives, the Labour
  Relations Act, the 2015 Marikana Commission report), but the post-1994 ANC alliance and Marikana
  are live, litigated, domestically contested politics. **Build it in Wave 2, with a reviewer.**

---

## Recommended build order, and why

**1 → Germany. 2 → Sweden & Denmark. 3 → Mexico. 4 → Poland. 5 → India. 6 → South Africa.
7 → South Korea. 8 → Brazil. 9 → Chile. 10 → Bangladesh. 11 → China. 12 → The Gulf.**

The reasoning:

- **Start with Germany and the Nordics** because they are the *easiest to source* and the *hardest to
  argue with*. They establish the track's credibility with primary-source material and near-zero
  political risk, and they teach the two habits the whole track depends on (*bargaining level
  explains coverage*; *look for the plumbing before the culture*).
- **Then Mexico**, early and deliberately, because the USMCA Rapid Response mechanism is the track's
  one piece of good news, and because it inoculates the student against the assumption that "a union
  exists" means "workers have a union."
- **Then Poland**, once the student has the vocabulary — Solidarity lands far harder *after* you know
  what a normal union is, because the point is what it wasn't.
- **India, South Africa, Korea, Brazil, Chile** widen the spectrum in the middle. India in particular
  should come before the Wave-3 courses, because "most workers have no employer" is the concept that
  makes the Gulf course legible rather than merely shocking.
- **Bangladesh, China and the Gulf go last** because they are the three where a sourcing failure
  would be most damaging, and because by then the method — statute first, dated claims, named
  disputes, motivated sources read against each other — will be established and repeatable.

**Track sequencing for the learner** is a different order from the build order. As a learning path:
*Know Your Rights at Work* (present-tense, practical) → **History of Unions** (the anchor and the
four questions) → any country courses in any order → **Chile last**, because "a labour system
designed to be weak" is the right final thought before a student goes and re-reads their own
country's statute.

---

## What BAM would need to build the hard ones responsibly

1. **A standing editorial rule for hostile-state and contested courses**, applied identically to
   China, the Gulf and Bangladesh:
   *statute or official text first · every claim dated · contested figures presented as contested,
   with the range and the dispute named · no advocacy claim laundered as fact · at least one
   independent monitor cited alongside any official source, and vice versa.*
   The anchor course already models this (Haymarket's bomb-thrower, Hoffa, the NLRA exclusion's
   motive, the Qatar reforms) — it is a proven pattern in this repo, not a new invention.
2. **A South African reviewer for the COSATU course** (Marikana is still litigated and the ANC
   alliance is a live domestic fight) — the same posture the repo already takes on the Hoodoo
   courses, which are held from publishing pending review by a knowledgeable member of the tradition.
3. **Translation capacity** for the Chile course (Spanish) and, to a lesser degree, Brazil
   (Portuguese) and Korea. Primary sources exist; they are not in English.
4. **A decision about the China course's evidence gap** — with China Labour Bulletin wound down since
   2023, there is no longer a good open dataset on Chinese strikes. Either build the course from the
   statute alone and *say so in the course*, or don't build it.
5. **Nothing else.** Waves 1 and 2 need no permissions, no reviewers (except South Africa), and no
   vendor — only authoring time. That is the argument for starting there.

---

## Cross-links

- Anchor course: \`scripts/data/history-of-unions-course.ts\` (branch \`content/history-of-unions\`).
- Companion: **Know Your Rights at Work** (branch \`content/know-your-rights-at-work\`).
- Category: **Culture & History** (the anchor ships there). If the track grows past ~4 courses,
  consider promoting it to its own **"Workers & Rights"** category with a learning path.
- Source note: \`plans/future-courses/history-of-unions.md\` (BAM's original ask — move to
  \`completed/\` once the anchor ships).`,
    provenance: "plans/future-courses/workers-rights-track-proposal.md",
  },
  {
    key: "world",
    title: "World",
    summary: "courses on:",
    body: `courses on:
- Pan-Africanism
- Afrocentricity
- Africa before colonization
- Central America Pre-Columbian
- Asia pre-colonization
-`,
    provenance: "plans/future-courses/world.md",
  },
];
