// GENERATED by `pnpm gen:future-work` from plans/future-courses/*.md (auto-discovered — add a .md, re-run, done) — DO NOT EDIT BY HAND.
// The source notes live in the gitignored `plans/` dir, so the content is committed here as
// plain strings: the deployed app imports this module and never reads the filesystem.

export interface ProposalDoc {
  /** Stable key: the filename without .md. Used as the /admin/future item key. */
  key: string;
  /** Human title: the doc's first `# heading`, else the de-slugged filename. */
  title: string;
  /** First real line of prose, for the card. */
  summary: string;
  body: string;
  provenance: string;
}

export const PROPOSAL_DOCS: ProposalDoc[] = [
  {
    key: "civics-more-proposal",
    title: "More civics courses — proposal (topic choice is BAM's to redirect)",
    summary: "Six high-value topics that fill gaps in the existing civics catalog (civics-101, us-constitution,",
    body: `# More civics courses — proposal (topic choice is BAM's to redirect)

Six high-value topics that fill gaps in the existing civics catalog (civics-101, us-constitution,
state-vs-federal, us-state-local-gov, how-to-run, help-a-campaign, spotting-misleading-marketing, +
50 states + DC). All would be non-partisan (process/institutions, no position on any bill/ruling).

## Drafted this session (shipped in \`bundle/content-courses-2026-07-09\`)
1. **How a Bill Becomes Law (Federal), in depth** — the existing civics-101 only covers it in a
   6-line overview; this is the full institutional process (committees, Rules Committee, filibuster/
   cloture/reconciliation, conference, veto/override).
2. **The Supreme Court & the Judicial Branch, in depth** — state-vs-federal uses cases to show the
   federalism split but never how the Court *operates*; this covers structure, cert, oral argument,
   opinions/precedent, interpretive approaches (neutrally), and checks on the judiciary.

## The 4 remaining candidates (not yet drafted — pick which to author next)
3. **The Bill of Rights / Know Your Rights (1st & 4th Amendment basics)** — a practical,
   plain-language walk through core rights (speech, religion, press, assembly; search/seizure) and
   what they do and don't cover. High everyday relevance; pairs with the civics + constitution courses.
4. **Voting & Elections 101** — how registration, primaries vs general, the Electoral College,
   ballot measures, and certification actually work. Non-partisan mechanics; complements the 50-state
   civics "how to take part" lessons with the national picture.
5. **Jury Duty & the Courts (the citizen's side)** — what a summons means, voir dire, grand vs petit
   juries, the trial process, and why jury service matters. A civic duty almost no course covers.
6. **Citizenship & Naturalization Basics** — who is a citizen, the naturalization process, the civics
   test, and the rights/responsibilities of citizenship. Useful for new-citizen and homeschool audiences.

**Recommendation:** #3 (Know Your Rights) and #4 (Voting & Elections 101) are the highest-leverage next
two — broadest everyday relevance and the most-requested civic-literacy gaps. #5 and #6 are strong
follow-ups. Tell Claude which to author.`,
    provenance: "plans/future-courses/civics-more-proposal.md",
  },
  {
    key: "history-of-unions",
    title: "History of unions",
    summary: "create a course on the history of history-of-unions",
    body: `create a course on the history of history-of-unions
in the US and abroad
create a track of courses that covers workers rights globally, with courses on different countries showing a diverse spectrum of how nations/states interact with labor`,
    provenance: "plans/future-courses/history-of-unions.md",
  },
  {
    key: "home-school-pricing-research",
    title: "Home-School Live BVC Pricing — Market Research (July 2026)",
    summary: "_Companion to `home-school-pricing.md` (the existing one-pager, tiers ~$20/$60/$150). This file is",
    body: `# Home-School Live BVC Pricing — Market Research (July 2026)

_Companion to \`home-school-pricing.md\` (the existing one-pager, tiers ~$20/$60/$150). This file is
the evidence base for that pager's numbers. Local research note — not for publication._

---

## 1. Comparables table

| Offering | What you get | Price | Per-unit basis | Source |
|---|---|---|---|---|
| **Outschool — group live class (guideline rate)** | Teacher-set live class, any format except 1:1 | **$17–21** per learner per hour (one-time/ongoing/short-course bands all cluster here; semester 8+ wk programs $18–20) | per student, per class-hour | [teach.outschool.com/insights/pricing](https://teach.outschool.com/insights/pricing/) |
| **Outschool — 1:1 tutoring (guideline rate)** | Private live tutoring | **$45–60/hr** (≤30 min sessions run $60–64/hr) | per student, per hour | [teach.outschool.com/insights/pricing](https://teach.outschool.com/insights/pricing/) |
| **Outschool — monthly membership (buyer side)** | Credit bundle a parent buys, spent on live/self-paced classes | **$40/mo** (~1 live class/wk) · $70/mo (~2/wk) · $120/mo (~3/wk) · $240/mo (~4/wk) | per student, per month | [brighterly.com/blog/outschool-pricing](https://brighterly.com/blog/outschool-pricing/) |
| **Outschool — 1:1 tutoring (market/actual)** | Private tutoring, promo-inclusive | $15–118 per lesson (national comparison: $25–80/hr) | per lesson | [brighterly.com/blog/outschool-pricing](https://brighterly.com/blog/outschool-pricing/) |
| **Prenda microschool — direct-pay** | Platform fee + a "guide" (facilitator) fee, full weekday microschool, not a single subject | **$219.90/mo** platform fee alone; guide fee typically $3,500–4,000/yr (~$290–333/mo) → **~$475–517/mo total** per student | per student, per month | [help.prenda.com — Financial Policies](https://help.prenda.com/knowledge/prenda-financial-policies-direct-pay-microschools) |
| **Primer microschool** | Full micro-private-school seat; heavily state-scholarship-funded | **$0–$3,200/yr** out-of-pocket depending on state/income (many families pay $0 via ESA/scholarship) | per student, per year | [primer.com/tuition](https://primer.com/tuition) |
| **Sora Schools** (full-time accredited online private school, grades 6–12 — ceiling reference, not a single-subject comparable) | Full course load, not enrichment | **$17,900/yr** full tuition; flexible-tuition band **$7,500–$16,000/yr** | per student, per year | [soraschools.com/tuition-and-affordability](https://soraschools.com/tuition-and-affordability) |
| **Small-group / online tutoring, general market** | Live tutoring, subject-dependent | **$20–60/hr** online average; by grade: K-2 $25–45, 3-5 $30–55, 6-8 $40–65, 9-12 $50–100/hr | per student, per hour | [brighterly.com/blog/tutoring-rates-per-hour](https://brighterly.com/blog/tutoring-rates-per-hour/) |
| **Homeschool co-op membership (typical)** | Parent-taught or paid-instructor classes, in-person hub | **$500–$3,000+/yr** all-in tuition; separately, registration $25–150/family, semester fee $70–140, building fee $125–350 | per family (+ per-class add-ons) | [numaschool.com — co-op fees](https://numaschool.com/learn/glossary/co-op-membership-fees), [tshanywhere.org — co-op tuition guide](https://www.tshanywhere.org/post/co-op-homeschool-tuition-fees-guide) |
| **Real 2026-27 co-op examples** | Registration/membership only (classes billed separately) | Joy Homeschool Co-op **$115/family**; TEACH (Tri-Cities) **$45/family**; Ignite Homeschool Co-op **$150/student** (2026-27) | per family or per student | [joyhomeschool.org](https://www.joyhomeschool.org/), [teachtricities.com](https://www.teachtricities.com/tn/teach/index.cfm), [ignitehomeschoolcoop.org](https://www.ignitehomeschoolcoop.org/registration/fees-tuition) |
| **Maven** (adult cohort-based courses — ceiling reference for "live cohort" premium, not a kids' comparable) | Multi-week live cohort with expert instructor, projects, community | **$500–$3,000/cohort** (avg ~$500; typical band $800–$2,500) | per person, per cohort/course | [maven.com/resources/course-price-and-length](https://maven.com/resources/course-price-and-length), [help.maven.com — pricing your course](https://help.maven.com/en/articles/6732396-pricing-your-course) |
| **Woke Homeschooling** (Black-history-adjacent, self-paced only — no live component) | Downloadable U.S.-history curriculum | Grades 3–7: **$50**; high-school (2 parts): **$60 each** — one-time purchase, not recurring | per curriculum, one-time | [wokehomeschooling.com](https://wokehomeschooling.com/) |
| **Gilder Lehrman Institute — self-paced African American History courses** | Lecture-based self-paced course w/ primary sources, quizzes | **$29.99** (affiliate-school network) / **$39.99** (general public) | per course, one-time | [gilderlehrman.org — self-paced courses](https://www.gilderlehrman.org/history-resources/curriculum/3-self-paced-courses-african-american-history) |
| **Cultural Roots Homeschool Co-Op** (Richmond, VA — culturally centered, closest live positioning to BVC) | Weekly à la carte classes centered on Black/Brown/Indigenous history & culture | **No public price found** — site frames participation via tax-deductible "Patron" donations, not a listed tuition/class fee | unknown | [culturalrootsco-op.com](https://culturalrootsco-op.com/) — **could not source a hard number** |
| **National Black Home Educators (NBHE)** | Support/resource network, co-op-formation help | No live-class pricing published (membership/resource-network model) | n/a | [nbhe.net](https://www.nbhe.net/) — **could not source a hard number** |

---

## 2. Synthesis — going rate by delivery model

**(a) Async/recorded access only.** There's no clean like-for-like: Outschool doesn't sell a pure
self-paced subscription, and the closest culturally-specific analogs (Woke Homeschooling, Gilder
Lehrman) are **one-time** purchases at **$30–$60**, not recurring. The nearest recurring proxy is a
co-op's per-family registration/semester fee amortized monthly (~$10–30/mo-equivalent). A recurring
$20–25/mo for ongoing access + quizzes + certificate + a monthly live group Q&A is defensible and, if
anything, priced conservatively against Outschool's cheapest bundle ($40/mo, which already includes
one weekly *live* class).

**(b) Weekly live group class.** Outschool's own guideline rate ($17–21/learner/hr) implies **~$68–84/
month** for one weekly 1-hour class billed à la carte; Outschool's packaged membership compresses
that to $40–70/mo because popular repeat classes are discounted inside the credit system. So the
real-world range for "weekly live group class" is **$60–90/month per student**, with $60–70/mo as the
most common lived price once bundled.

**(c) Live + small-group + parent reporting/light 1:1.** This sits between a large-group live class
and true 1:1 tutoring. Small-group tutoring commands a discount off solo rates (one source cites
~70% lower cost than 1:1 for similar gains) but is still meaningfully above a big-group class —
figure **$100–200/month** per student for a weekly small-group session, before adding the reporting
layer. Full 1:1 tutoring ($45–118/hr) and full-time microschool tuition ($475–1,500+/mo) sit well
above this and confirm there's plenty of headroom — a $150/mo "guided" tier is nowhere near the
ceiling this market will bear.

**Ceiling reference:** Families who've already looked at Prenda (~$475–517/mo), Sora ($1,492/mo
equivalent), or private tutoring ($45+/hr) will not blink at $150/mo for one subject's live +
guided offering — it reads as a small fraction of a full alternative-schooling budget.

---

## 3. Recommended 3 tiers for BVC home-school

All tiers priced **per student, per month** (matches Outschool's dominant convention and avoids the
per-family ambiguity co-ops have — see risk note below). Season equivalents assume a ~10–12-week
Season 1 run.

| | **Explorer (Low)** | **Cohort (Mid) — ⭐ ANCHOR** | **Guided (High)** |
|---|---|---|---|
| **Price** | **$20–25/student/mo** | **$60/student/mo** (~$150–180/season) | **$150/student/mo** (~$750/season) |
| **Positioned against** | Priced under Outschool's cheapest live bundle ($40/mo); above one-time self-paced curricula ($30–60) because it's recurring + monthly live | Sits exactly inside the Outschool weekly-live-class real-world range ($60–90/mo) | Below small-group-tutoring-plus-reporting ($100–200+/mo) and far below 1:1 tutoring or microschool tuition |
| **What's included** | Self-paced Season 1 course + Commodity Map; quizzes + certificate; **monthly** live group Q&A | Everything in Explorer + **weekly** live class (cohort-sized group) via \`/live\`; quick-check assignments | Everything in Cohort + **weekly small-group live** (capped roster) + full capstone project with feedback + parent progress reports (attendance/grades via the upcoming Family view) |
| **What Learn.WitUS already delivers** | Recorded course, quizzes, certificate | + cohorts, \`/live\` | + \`/live\` small-group cap, + Family view (in progress) is the differentiator no comparable at this price offers |

**Anchor the Mid tier.** $60/mo is the best-evidenced number in this set — it's not an estimate, it's
where Outschool's own guideline rate and its packaged membership price converge. Lead pricing
conversations with Cohort, then show Explorer as "try it first" and Guided as "if you want feedback
and reporting."

---

## 4. Validation note

**Ask the parent:**
1. *"How many kids total (your child + classmates), and would a per-child monthly price work, or
   would you rather I quote one flat price for the whole group?"* — tests per-student vs. per-family
   pricing tolerance and locks the group size before quoting.
2. *"What have you paid (or budgeted) for a comparable class — an Outschool course, a co-op class, or
   a tutor — for a similar subject?"* — anchors to her actual revealed willingness-to-pay instead of
   market averages, and surfaces whether she's benchmarking against $40/mo Outschool bundles (cohort
   tier will look pricier) or $500–3,000/yr co-op tuition (cohort tier will look cheap).

**Pricing risks:**
- **Per-family vs. per-child.** Co-ops mostly price per-family; Outschool prices per-child. If the
  "classmates" are a fixed small group (not open enrollment), a flat group rate (e.g., "$X/week for
  up to 6 kids") may land better than strict per-seat pricing — decide before quoting.
- **Sibling / group discount.** Comparable co-ops routinely stack registration + semester + per-class
  fees; a simple 10–15% discount for 3+ students from one family (or one classmate group) is
  standard practice and should be pre-built into the quote, not negotiated ad hoc.
- **Free trial.** Outschool gives new users 40 free credits (~1 class); co-ops often waive the first
  session. A free first live session lowers the parent's risk and matches category norms.
- **Anchoring mismatch.** If she's already compared BVC to Outschool's $40/mo entry tier rather than
  the $60–90/mo real weekly-live rate, the Cohort tier may need the "here's what a weekly live class
  actually costs elsewhere" framing from §2(b) above.

---

## 5. Verdict on the existing $20 / $60 / $150 one-pager

| Tier | Existing price | Evidence says | Recommendation |
|---|---|---|---|
| **Explorer** | ~$20/mo | Slightly under Outschool's cheapest live bundle ($40/mo) and in line with amortized co-op registration fees; no direct pure-async comparable to test against | **Keep, or nudge to $25/mo.** Evidence does not support lowering. |
| **Cohort** | ~$60/mo (~$150/season) | Matches the real-world weekly-live-class range ($60–90/mo) almost exactly | **Keep as-is — this is the best-supported number in the set.** |
| **Guided** | ~$150/mo (~$750/season) | Below the $100–200+/mo small-group-plus-reporting comparable band's upper end, and far below 1:1 tutoring/microschool ceilings | **Keep. There is headroom to test higher ($175–200/mo) if the parent reporting/Family-view feature lands as a strong differentiator, but $150 is defensible today.** |

---

## Numbers I could NOT source (flagged, not invented)

- **Cultural Roots Homeschool Co-Op** (Richmond, VA) — the single closest live, culturally-centered
  comparable to BVC — publishes no tuition/class price; site framing is donation/"Patron"-based.
- **National Black Home Educators** — resource/support network, no live-class pricing model found.
- **Outschool actual realized multi-week-course total price** — only the per-hour guideline rate and
  a rough illustrative example ($50 for a 4-week series) were found; Outschool doesn't publish an
  aggregate average because every teacher sets their own price.
- **Sora Schools single-subject/enrichment add-on pricing** — only full-enrollment annual tuition was
  found; no per-course or drop-in rate.`,
    provenance: "plans/future-courses/home-school-pricing-research.md",
  },
  {
    key: "home-school-pricing",
    title: "Live BVC Classes for Homeschoolers — one-pager",
    summary: "_Send-ready draft. Also as a print-to-PDF page: `home-school-pricing.html` (open → Cmd/Ctrl-P → Save as PDF)._",
    body: `# Live BVC Classes for Homeschoolers — one-pager

_Send-ready draft. Also as a print-to-PDF page: \`home-school-pricing.html\` (open → Cmd/Ctrl-P → Save as PDF)._

---

## Live Better Vice Club, taught by Brand Anthony McDonald
**On Learn.WitUS.Online — cited, media-rich lessons + a live class with the instructor.**

Your student joins **Better Vice Club: Season 1** — the story of how everyday commodities (coffee, tea,
chocolate, sugar, and more) shaped world history, geography, and culture — on an interactive **Commodity
Map**. Self-paced lessons at home, plus **live sessions** with me for discussion, questions, and projects.

**How it works:** each student gets a free login, enrolls in the class, works through the lessons at home,
and joins the scheduled **live class** (video + Q&A). Progress, quizzes, and a certificate are built in.

---

### Three ways to join

| | **Explorer** | **Cohort** ⭐ | **Guided** |
|---|---|---|---|
| **Best for** | Independent learners | A homeschool class/co-op | Students who want feedback |
| **Self-paced Season-1 course + map** | ✓ | ✓ | ✓ |
| **Live class with the instructor** | Monthly group Q&A | **Weekly live class** | **Weekly small-group live** |
| **Quizzes + certificate** | ✓ | ✓ | ✓ |
| **Graded assignments / project feedback** | — | Quick-check | **Full capstone + feedback** |
| **Parent progress dashboard** (grades + attendance) | — | — | ✓ |
| **Price (per student)** | **$20/mo** | **$60/mo** _(or $150/season)_ | **$150/mo** _(or $750/season)_ |

_**First live session is free.** **Sibling/classmate discount:** 10–15% off for 3+ students from one
family or group. Larger co-ops (5+): ask about a group rate._

---

### Why families like it
- **Cited & honest** — every claim ties to a real source (APA), so it meets homeschool-portfolio standards.
- **One story, many subjects** — history, geography, economics, and culture in one thread.
- **Interactive** — the Commodity Map lets kids explore where each story begins.
- **A real teacher** — live time with the instructor, not just videos.

### Getting started
1. I set up your class group and send each student a login.
2. Students enroll and start Season 1 at their own pace.
3. We hold the first live session and set a weekly time.

**Contact:** _[your email / booking link]_ · **Learn.WitUS.Online**

---

_Notes (internal): pricing validated against 2026 comparables (\`home-school-pricing-research.md\`) —
Outschool live ~$17–21/learner-hr & $40–240/mo bundles, co-ops $45–150/family, microschools as the
ceiling. **$60 Cohort is the best-anchored tier** (matches the real weekly-live rate); Guided has
headroom to test $175–200. Live now runs **in-app**: the app hosts the course, Commodity Map,
**live class + live chat + "who's here" roster**, recordings (ViLoud embed), quizzes, certificates,
and the **parent Family view** (a linked parent sees their own child's progress, grades, and
attendance — powers the Guided tier's progress dashboard). Kid-friendly avatar+PIN login is available
for young students without email._`,
    provenance: "plans/future-courses/home-school-pricing.md",
  },
  {
    key: "travel-abroad-proposal",
    title: "Travel & Living Abroad — course track proposal (from the US)",
    summary: "A new \"Travel & Living Abroad\" category. Two courses are building now; the rest are proposals —",
    body: `# Travel & Living Abroad — course track proposal (from the US)

A new **"Travel & Living Abroad"** category. Two courses are building now; the rest are proposals —
pick which to author. All cited from authoritative gov sources (travel.state.gov, CDC, CBP, IRS,
USCIS, SSA), all stressing "verify current rules/fees at the official source" since these change.

## Building now
1. **How to Get a U.S. Passport** — book vs. **card** (dedicated section: card is land/sea only, NOT
   international air), first-time (DS-11) vs. renewal (DS-82), documents, fees, expedited, minors,
   lost/stolen, the 6-month-validity rule. _(travel.state.gov)_
2. **Travel Visas 101** — how to figure out and get a visa for any destination as a US traveler:
   visa-free / visa-on-arrival / e-visa / embassy, Schengen + **ETIAS**, documents, a repeatable
   research checklist. _(travel.state.gov country pages, EU/ETIAS, embassy sites)_

## Proposed — Short trips & tourism (traveling FROM the US)
3. **International Travel Basics** — the whole pre-trip checklist tying passport + visa + insurance +
   health + money + **STEP enrollment** (Smart Traveler) + itinerary together. The "start here" hub.
4. **Travel Health & Safety** — CDC destination vaccines & health notices, travel insurance, staying
   safe, what to do in an emergency abroad (embassy/consulate help). _(CDC Travelers' Health, State Dept)_
5. **Money Abroad** — currency, cards vs. cash, foreign-transaction & ATM fees, avoiding scams,
   notifying your bank. _(CFPB, FTC)_
6. **Flying Internationally & Coming Home** — airports/customs, **CBP re-entry**, **Global Entry /
   TSA PreCheck / Trusted Traveler**, and **what you can (and can't) bring back** (duty, ag/food rules).
   _(CBP, TSA)_
7. **Culture & Language Ready** — cultural etiquette, basic language prep, respectful travel. (Pairs
   with the existing Languages atlas + language courses.)

## Proposed — Moving & living abroad (long-term)
8. **Moving Abroad 101** — the big decisions: tourist stay vs. **residency** vs. citizenship, types of
   long-stay/retirement/work visas, choosing a country, the realistic timeline & costs. The hub course.
9. **Working Abroad & Digital-Nomad Visas** — work permits, employer sponsorship, the wave of
   **remote-work/digital-nomad visas**, and what they do/don't allow.
10. **Taxes for Americans Abroad** — the big one: the US taxes citizens on **worldwide income** even
    abroad. Covers the **Foreign Earned Income Exclusion**, **FBAR**, **FATCA**, foreign tax credit,
    filing deadlines. High-value, high-anxiety topic. _(IRS — cite carefully; "consult a tax pro.")_
11. **Banking & Money When You Live Abroad** — how **FATCA** affects opening foreign accounts,
    keeping US accounts, transferring money, currency risk. _(IRS/Treasury, CFPB)_
12. **Healthcare Abroad** — international/expat health insurance, how care differs, Medicare doesn't
    travel, planning for prescriptions & emergencies.
13. **Retiring Abroad** — **Social Security payments while overseas** (SSA), residency/retirement
    visas, taxes + healthcare for retirees, cost-of-living. _(SSA, State Dept)_
14. **Studying Abroad** — programs, student visas, safety, credit transfer, funding.
15. **Dual Citizenship & Renunciation basics** — what dual citizenship is, how the US treats it, and
    the (rare, serious) renunciation process. _(State Dept)_
16. **Shipping & Logistics of an International Move** — movers vs. ship-it-yourself, customs on your
    goods, pets, what to sell/store, mail forwarding & voting from abroad.

## Recommended sequencing
- **Now:** Passport + Visas (building).
- **Next (short-trip pillar):** #3 International Travel Basics (the hub) + #6 Flying & Coming Home
  (Global Entry / customs) — highest everyday demand.
- **Then (moving pillar):** #8 Moving Abroad 101 (hub) + #10 Taxes for Americans Abroad (the topic
  people most fear getting wrong).
- The rest as demand shows.

## Note
The tax/legal/immigration courses must be firmly framed as **educational, not professional advice**
(the new site-wide disclaimer already covers this) and point to IRS/USCIS/a licensed professional.`,
    provenance: "plans/future-courses/travel-abroad-proposal.md",
  },
];
